10up/ElasticPress

- classes/class-ep-api.php
- classes/class-ep-wp-query-integration.php
Fixes #186. Remove the index exists check by moving the search to an earlier filter in query execution. We then save the search to an associate array using a unique query hash as the key. If search fails, it will return false and we will revert to MySQL. If search is successful but returns 0 results from ES, we will just show 0 results.
> Remove index exists check

- classes/class-ep-wp-query-integration.php
WordPress core search enforces limiting the post types searched to just those without the 'exclude_from_search' flag turned on when it would otherwise be 'any', but previously ElasticPress didn't enforce this limit at all, and just opened up to any post type if one wasn't specified already.
This PR does the following:
1. If we're doing a search for 'any' post, default to post types not excluded from search.
2. For all other query types (not search), continue to allow querying across all indexed post types.
> Abide by the 'exclude_from_search' flag when running search queries.

- .travis.yml
- classes/class-ep-api.php
This PR simply makes request arguments for more important requests filterable. It also extends `index_post` timeout to 15 seconds and `bulk_index_posts` to 30 seconds. There have been two reports of the default 5 second timeout being too short. This should hopefully remedy that.
See #204
> Make request arguments filterable. Also extend timeout for indexing requests

- README.md
- classes/class-ep-api.php
- tests/test-single-site.php
PR adds support for `date` in orderby and adds a unit test.
> Support date in orderby - closes #203

- classes/class-ep-api.php
- classes/class-ep-sync-manager.php
Remove duplicate `ep_post_sync_args` filter and add `ep_prepare_post_args` filter. If ep_post_sync_args is empty, don't sync
> Remove duplicates filters and allow sync post termination

- classes/class-ep-wp-query-integration.php
By default no integration will happen on admin ajax. This PR add a filter for this.
> Allow for filtered query integration on admin ajax requests

- bin/wp-cli.php
cleared failed_posts array after email is sent, to not send it only for one site for #232
> cleared failed_posts array after errors email is sent

- classes/class-ep-wp-query-integration.php
- tests/test-multisite.php
fix for #235 
Just passing post ID as argument to get_post will override some data in the initial post object and will not work on multisite, but it's better to use as it will return all possible fields. Then merging it with the initial object populates all fields and keeps the initial values.
I've added additional function to make this method work for multisite as well.
> use post id in get_post to enrich the post object and make it possible for multisite

- README.md
- bin/wp-cli.php
This allows to resume a index action when failed or stopped before finishing, without restarting the index operation.
> Add --offset paramater to cli index command

- classes/class-ep-wp-query-integration.php
- tests/test-multisite.php
The `post_excerpt` and `post_author` fields were not set in the query integration causing `the_author()` and related functions to fail and `the_excerpt()` to handle the excerpt like there is none.
> Fix fields not loaded from elasticsearch query

- README.md
- bin/wp-cli.php
This allows to resume a index action when failed or stopped before finishing, without restarting the index operation.
Redo of #266 :)
> Add --offset argument to cli index command

- classes/class-ep-api.php
Hi,
I need use the $post->post_modified as the default sortorder and I havn't found a way to do this. It would be great if you add this feature to your plugin.
Thanks for the great work, Hannes
> Adding filter to set default sortorder

- classes/class-ep-api.php
- Main query can actually do a like query to meta data. However,
sometimes we need to have both main query and meta data query. They
are, of course, different, hence, it would be great if we can use meta
data query as a filter for main query and this meta data query supports
LIKE rather than normal ‘term’ filter.
> Enhancement for #263 Support like query in metadata, in addition with main query

- classes/class-ep-sync-manager.php
Hi! 
Right now a post would sync using the `transition_post_status` action which is a little early for other plugin (I'm looking at you ACF!). This would therefore not save all updated information on post metas.
Using the `wp_insert_post` action with a low priority would let all other plugin hook before we actually sync with the ElasticSearch index.
Any feedback greatly accepted!
Cheers!
> Change sync hook

- bin/wp-cli.php
See #291 
Adds action prior to `wp-cli index` command main logic
> Add action prior to index command

- bin/wp-cli.php
- classes/class-ep-api.php
- New Filter `ep_indexable_sites_args` to allow control over the whole `wp_get_sites`
- Easy usage of --network-wide=INT to change the limit, defaults to 0 where it has no LIMIT
_Resolve:_ #272
> Include arguments to the ep_get_sites

- classes/class-ep-sync-manager.php
It would be helpful to have a method that does the opposite of `setup()` for removing the sync hooks. The use case being I want local dev instances of sites to use the live Elasticsearch index but I don't want post updates/deletions on my local set-up to propagate to the production index.
Adding a method to this class would simplify things since when new hooks are added to ElasticPress, I wouldn't need to keep up with the changes. I could just call one method and be done with it.
> Added a `destroy()` method

- classes/class-ep-api.php
- tests/test-single-site.php
WordPress supports searches via the `category_name` argument. The arg is set on pages like example.com/category/foo/?s=bar.
I think ElasticPress should support this type of queries too.
Workaround:
```php
add_filter( 'ep_formatted_args', 'ds_category_name_searches', 10, 2 );
function ds_category_name_searches( $formatted_args, $args ) {
if ( ! empty( $args[ 'category_name' ] ) ) {
$terms_obj = array(
'terms.category.slug' => array( $args[ 'category_name' ] ),
);
$formatted_args['filter']['and'][]['bool']['must'] = array(
'terms' => $terms_obj
);
}
return $formatted_args;
}
> Add support for category_name queries

- tests/bootstrap.php
- tests/includes/class-ep-test-base.php
- tests/includes/functions.php
- tests/test-multisite.php
- tests/test-single-site.php
This reverts parts of e8c82bb3c72617dd4db19513bb3eadc58cb748cd since `ABSPATH` isn't (always) defined for tests, especially not in `tests/bootstrap.php`.
> Run unit tests again.

- bin/wp-cli.php
- classes/class-ep-api.php
In #249 the option for a security header (API key) was added however it does not function on the stats and status calls when called by WP-CLI as these calls don't use the header. This fixes the issue and adds a callable function for getting the headers in future classes.
> WP_CLI GET Calls missing headers

- classes/class-ep-wp-query-integration.php
- tests/test-single-site.php
Issue #306 shows that there are PHP notices due to array keys not existing in the $post_array. To test, I utilized the ep_search_post_return_args filter to add a fake_item to the $post_return_args array. If the item in the array does not exist, the test will error out. 
The resolution for this was to add an isset() conditional to verify that the key exists in the $post_array.
> Resolves PHP notices post 1.5 upgrade.

- classes/class-ep-api.php
Adds a filter to search results to allow filtering of results after retrieval from ES.
When making use of filtering request_args for the search function many of the return variables (such as search term highlighting) will modify the response in ways that aren't easily accounted without being able to modify the return data. This filter adds in the ability to filter the return data while adding the initial response thereby allowing the developer to better make use of the various modifications that are enabled with the 'ep_search_request_args' filter.
> Add filter to search results

- classes/class-ep-api.php
By filtering the _source array when building the posts in the API class, this provides the ability to pass data from the Elasticsearch hit to the view. Our use case is to pass the `_score` and `highlight` for rendering in search results. 
**Example usage:**
```php
add_filter( 'ep_retrieve_the_post', function ( $post, $hit ) {
$post['score'] = $hit['_score'];
return $post;
}, 10, 2 );
```
Currently, the best way to handle this is to leverage the `ep_retrieve_raw_response` action, but that necessitates rewriting functionality from the `EP_WP_Query_Integration` class (maintaining the `$query_stack`, preparing the posts, filtering `the_posts`, etc.). This new filter would provide an easier way to accomplish this.
We’ve also submitted [a PR](https://github.com/wpengine/wpe-search/pull/31) on …
> Filter the _source post array from Elasticsearch

- bin/wp-cli.php
Added the `ep_post_sync_kill` filter when queing posts too, otherwise they get indexed anyway.
> Use the `ep_post_sync_kill` filter for bulk index

- classes/class-ep-api.php
After running ep_get_host() the elasticsearch_alive() method will still attempt to reach the host even if a wp_error is returned due to a failure of all available hosts. This fix will force a 2nd host check for backups and then return false instead of the wp_error();
> Extra check for proper host.

- classes/class-ep-api.php
- tests/test-single-site.php
- Draft, pending, auto-draft post will have post_date_gmt set to:
“0000-00-00 00:00:00”. This value is not parseable by ElasticSearch,
hence, we will need to set it to null value to get indexing gone
through.
http://cl.ly/image/2J2U0H3u2f3c
- This will also apply for post_modified_gmt
> Allow indexing for posts have "0000-00-00 00:00:00" date value

- classes/class-ep-config.php
- tests/includes/class-ep-test-base.php
- tests/test-single-site.php
Update to get_indexable_post_types() to only return post types that have exclude_from_search set to false and a unit test to verify.
> Indexable post type check for exclude_from_search. (fixes #321)

- includes/mappings.php
A quick fix to eliminate PHP_CodeSniffer errors (when using WordPress coding standards) in the mapping file due to inconsistent formatting.
> Fixes PHP_CodeSniffer Errors

- classes/class-ep-api.php
The ep_search_request_args is handy but, as it is applied after the args themselves are encoded it is rather innefficient. This allows for the filtering of args as they're encoded.
> Add filter before args are encoded

- classes/class-ep-sync-manager.php
- tests/test-single-site.php
When you hit post-new.php, WP will create a post with the post status of auto-draft. When the wp_insert_post action is fired, EP will try to delete the post from the index and will fail. This PR will prevent the HTTP request from occurring if the post status is auto-draft.
> Aborts sync when post status is auto-draft. Unit test included.

- classes/class-ep-api.php
- tests/test-single-site.php
> Order non-search queries by date if no orderby passed in

- classes/class-ep-api.php
When working with some plugins, such as post-to-posts and others, if there is a need to index information not part of the post itself, such as a connection title in the above scenario, it becomes difficult to do so without significantly modifying post meta or other aspects. This, among other uses, allows for the filtering of information sent to ElasticSearch at the last moment before the request is made.
> Add filter to modify indexed data before object is sent to ElasticSearch

- classes/class-ep-api.php
The search() method takes the parameter $scope which defaults to 'current' but the accessor, ep_search(), was using $cross_site = false as the second parameter. This updates ep_search to be consistent with search().
> Fix ep_search() argument

- README.md
- bin/wp-cli.php
When running a bulk index troubleshoot the individual errors in posts that fail to index can be problematic. This makes it a bit easier by adding a --show-bulk-errors param to display the error message along with the post that failed to index.
> Add failure details.

- bin/install-wp-tests.sh
- tests/includes/class-ep-test-base.php
Replaces #375 and adds support for WP 3.8 tests.
> Use proper tests checkout for WP_VERSION=latest w/ WP 3.8 support

- bin/wp-cli.php
If all posts are killed (via ep_post_sync_kill) indexing will end with an error. This prevents that from happening by simply not calling bulk_index if it isn't needed.
> Fixes an error that could occur if all posts are killed.

- includes/mappings.php
It turns out that snowball (http://snowball.tartarus.org/) doesn't support the same languages as Lucene so, for example, using ep_analyzer_language of arabic will work for the analyzer but causes a crash on the snowball filter. This adds a 2nd param to the filter to specify which spot it is filtering allowing the ability to avoid issues.
> Specify language filter

- elasticpress.php
- includes/mappings.php
- readme.txt
This fix does two things:
* Removes the fields field type from object typed fields as they should be called properties.
* Remove path from object field types.
Dockunit is upgrading to ES 2.0.0 today. Not sure where Travis CI is at, but at least we can see it's backwards compat.
> (Version 1.6.1) Make mapping compatible with Elasticsearch version 2.0.0

- bin/wp-cli.php
In some situations ElasticPress wp-cli index doesn't index all posts.
How to reproduce it:
- clear posts from your WordPress
- use wp-cli to generate some content
```
wp --allow-root post generate --count=2500 --post_author=some_author
```
- run above command one more time - wait few seconds before doing this again
- run index command
```
wp elasticpress index --setup
```
Go to your Elasticsearch and check number of documents. Expected number should be 5000
Command result:
> Number of posts synced on site 1: 5000
Total time elapsed: 23.017
Warning: ElasticPress is already activated.
Success: Done!
Elasticsearch data
This comes from the fact that by default posts are ordered by `post_date` column which doesn't have to be unique (and `wp post generate` generates all posts with the same …
> Use order by unique key - ID

- README.md
- classes/class-ep-api.php
- classes/class-ep-wp-query-integration.php
- includes/mappings.php
- readme.txt
- tests/test-single-site.php
Added new dynamic template mapping for long, double, date, datetime, time as well -- same as #372
> Remap meta mappings for extensive `type` usage

- README.md
- classes/class-ep-api.php
- tests/test-single-site.php
This ticket is in response to #338.
Unfortunately, due to limitations of Elasticsearch we cannot store unserialized meta objects and arrays. We can however serialize them in case anyone needs that information. Right now our mapping is limited to storing boolean, integer, long, double, and string (possibly float not sure).
This PR fixes a line of useless code that was unserializing an array every time. It also does a check on each meta value. If it's an array or object, it serializes. If not, it simply indexes the value. A slew of tests have been added to test this code and the general meta mapping.
Down the road I can see us improving the mapping a bit, but this PR maintains backwards compatibility.
@ChrisWiegman @allan23 can you review?
> Meta Formatting Fixes

- README.md
- bin/wp-cli.php
Also cleans up private _index_helper() method to support more args long term.
Usage:
`wp elasticpress index --post-type="my_cpt1,my_cpt3"`
The example above will only index `my_cpt1` and `my_cpt3`, it will not index `my_cpt2` or `post` or any other indexable post type that may be registered. Super handy for splitting up large indexing jobs into multiple processes.
> WP-CLI index by post type

- classes/class-ep-api.php
In version 1.6.2, the ```fuzzy_like_this``` param was removed, as it's deprecated in elasticsearch. The ```min_similarity``` field was also removed and replaced with the ```fuzziness``` field. This field had a filter around it so you could modify these results a bit. This adds a new filter around the new ```fuzziness``` field to give you the same freedom.
> Add a filter around the second fuzziness argument

- bin/wp-cli.php
Fixes error "Fatal error: Cannot access private property WP_Object_Cache::$cache". Internally this methods does the same thing, see https://developer.wordpress.org/reference/classes/wp_object_cache/flush/
> Fix for wp_cache_flush

- classes/class-ep-api.php
This let's us do the following:
* Track the time taken for each query
* Log broken hosts
* Track the amount of EP queries per page
* Track actual arguments being sent to Elasticsearch
> Log queries for debugging

- classes/class-ep-api.php
Simple bug fix. `size=-1` does not work in Elasticsearch.
> Use max int for posts_per_page=-1

- README.md
- classes/class-ep-api.php
- tests/test-single-site.php
As the title says this allows us to support arbitrary document paths in `orderby`. This in turn allows someone to easily order by post meta. Includes tests.
@ChrisWiegman please review.
> Support arbitrary document paths in orderby

- classes/class-ep-api.php
In a meta query (not a search query), we should check the `raw` property instead of `value`. `value` is analyzed which is not needed for non-search.
@allan23 please review.
> By default check raw meta query value for meta_query

- .travis.yml
- bin/install-wp-tests.sh
- phpunit.xml
WordPress supports mysqli by default as of 3.9, so we only need this dropin for 3.8 (at least, that's the lowest version we test for in our travis matrix). We also need to make sure we're grabbing the legacy version (the actual dropin) since the one downloaded only defines a constant telling WordPress not to use the mysql_* functions.
> Only download MySQLi dropin when it's needed

- classes/class-ep-api.php
With ElasticPress installed but no host running, the untrailingslashit() call was being passed a WP_Error object and causing a PHP warning.  
```
PHP Warning:  rtrim() expects parameter 1 to be string, object
given in /srv/www/test-site/htdocs/wp-includes/formatting.php on line 1995
```
This update moves the slashit call to $request_url after the is_wp_error() check.
Backtrace of the warning:
```
array(20) {
[0]=>
array(4) {
["file"]=>
string(61) "/srv/www/test-site/htdocs/wp-includes/formatting.php"
["line"]=>
int(1980)
["function"]=>
string(17) "untrailingslashit"
["args"]=>
array(1) {
[0]=>
object(WP_Error)#476 (2) {
["errors"]=>
array(1) {
["elasticpress"]=>
array(1) {
[0]=>
string(26) "No running host available."
}
}
["error_data"]=>
array(0) {
}
}
}
}
[1]=>
array(4) {
["file"]=> …
```
> moved the request_url update to after the is_wp_error() check in remote_request()

- README.md
- bin/wp-cli.php
Sometimes it would be very useful not to disable ElasticPress search integration during wp-cli indexing operation. The reason behind this feature is that sometimes there is a need to reindex site and keep using ElasticPress turned on as reindexing may take very long time (1-2 hours).
> Add option not to disable ElasticPress while indexing

- bin/wp-cli.php
7bbc66c introduced a `wp_cache_flush` call after every index batch. In the context of the default core `$wp_object_cache` object, this makes sense, since it just clears the `cache` property on the php object. 
In the case of external object cache drop-ins, this also flushes the external object cache, which is not ideal. Originally, we had to switch from setting `$wp_object_cache->cache = array();` because the property is sometimes private or protected - to get around this, I check first to make sure its public, then set it to an empty array to save on memory usage.
In the case of the default class, the `cache` property is private, but `wp_using_ext_object_cache()` will return false, so in THAT case, we can just call `wp_cache_flush()` since it will just reset the `cache` property in that …
> Improve memory usage during indexing / Fix unnecessary cache flushes

- classes/class-ep-config.php
- classes/class-ep-wp-query-integration.php
Switching this out allows the `any` query to match the indexed post types. Because the [function](https://github.com/rossluebe/ElasticPress/blob/develop/classes/class-ep-config.php#L115-L119) already returns `get_post_types( array( 'exclude_from_search' => false ) );`, this will only affect users who have made changes to the indexable post types through the `ep_indexable_post_types` filter.
> Sync searchable_post_types with indexable_post_types.

- bin/wp-cli.php
- classes/class-ep-api.php
Those changes reduces memory consuption during indexing. wp-cli memory usage was growing until process was killed by Out Of Memory exception. I've added query logging only when WP_DEBUG is enabled. RIght now wp-cli doesn't use more than 50M even when indexing large datasets.
> Reduce memory consumption during indexing

- classes/class-ep-api.php
Define the constant ES_SHIELD in your wp-config.php
**Format:** `username:password` (colon separated)
**Example:** `define( 'ES_SHIELD', 'es_admin:password' );`
> Adds Elasticearch Shield username:password login authentication. Fixes #441

- bin/wp-cli.php
Currently, running `wp elasticpress status` will fail if on Elasticsearch 2.1 or higher (maybe lower versions as well). Looking through the docs, that command was deprecated in [version 1.2.0](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/indices-status.html), and the recommendation is to use the `_recovery` API, which is what this PR does. Fixes #433
> Fix Status Command. Fixes #433

- classes/class-ep-api.php
- elasticpress.php
This PR solved issue reported in #478 
This seems to be the simplest solution to enable query logging even if `WP_DEBUG` is not enabled. 
I think it would be better if `Debug Bar ElasticPress` plugin would have defined some named constant like `define( 'DEBUG_BAR_ELASTICPRESS_ENABLED', true );` then this PR could use it instead of checking if `Debug Bar ElasticPress` plugin is enabled.
@tlovett1 & @allan23  if you don't like this approach I can go with proposed one - new option on GUI settings page with enabling debug mode via option.
> (Closes #478) Enable query logging

- classes/class-ep-api.php
Let's skip `category_name` entirely if `tax_query` has already been provided as a query argument. WP_Query has some [quirky backward compat functionality](https://core.trac.wordpress.org/browser/tags/4.5.1/src/wp-includes/query.php#L2872) that will fill `category_name` if the category taxonomy is provided within `tax_query` which leads to duplicate filters.
@dkotter or @allan23 can you review?
> Ignore category_name if tax_query is provided.

- elasticpress.php
Should use `require_once` instead of `require` to avoid `PHP Fatal error: Cannot redeclare class` error. This is something actually has happened for me.
> Small patch for elasticpress.php, should use require_once instead of require. 

- classes/class-ep-api.php
Double slash // prevents ES from deleting documents from index.
> (Closes #503) Removed slash

- classes/class-ep-api.php
Currently if you are on a single site within the network and only that site has the plugin enabled the GUI will not work as its trying to retrieve the network alias. This pull request adds a check in the get_index_status method to make sure the plugin is network enabled before it returns the network alias. 
@tlovett1 In order for the checkbox to appear now a user has to run the index. After the index is ran the checkbox will appear on the next refresh.
> Multisite GUI not working when plugin is not network enabled

- classes/class-ep-api.php
This PR is not ready for merge but rather review. @allan23 @ChrisWiegman @lukaspawlik @dkotter @AaronHolbrook 
Here are the proposed changes:
1. Decrease fuzzy clause fuzziness to 1 from 2. With a fuzziness of 2, the word yell matches yeti since they are two levenshtein changes apart. The point of fuzziness is to account for misspellings which 1 does for the most part. 2 is resulting in way too many bad results.
2. Add `operator => 'and'` to `multi_match` clause. Right now any document containing ANY of the search terms returns a match with a 2x boost. Let's only give the 2x boost to docs that contain ALL the terms.
3. Finally, add a `multi_match` query of type `phrase`. This clause gives a 4x boost to documents containing the terms exactly as is in the EXACT order.
P.S. If anyone wants a …
> Tweak search algorithm for more relevant results

- classes/class-ep-api.php
After running into some issues with debugging requests/responses from ElasticSearch, this seems like it would be a handy addition to allow other plugins to hook into this to perform more robust logging without requiring debug turned on or the user to be logged in (based on https://github.com/10up/ElasticPress/commit/82acd71e0a948782da42ae2505ea0d0c4b415755)
> added do_action( 'ep_add_query_log' ) to _add_query_log

- classes/class-ep-sync-manager.php
This is critical for syncing content created by non-admins (WooCommerce orders on the front end).
> Add kill filter for sync permissions checks

- classes/class-ep-sync-manager.php
- tests/test-single-site.php
Right now, when post meta is updated using `update_post_meta`, the updated meta is not sent to Elasticsearch. This is unexpected behavior and causes a huge problem for WooCommerce when stock counts are updated for purchased products.
This PR queues posts for syncing every time whitelisted meta is updated on a whitelisted post type. On shutdown all queued posts are synced. We do the sync on shutdown in case the same post has multiple meta keys updated.
Please review and post feedback on the problem as well as my solution. Pay special attention to the permission checking I'm doing. Also this needs unit tests if anyone wants to write them.
> Post meta updates not being indexed

- bin/wp-cli.php
There was no significant memory savings by having this here because of
the stop_the_insanity method, and removing it speeds up indexing
significantly
> Allow caching results of WP_Query during index. Fixes #453

- elasticpress.php
- tests/includes/class-ep-test-base.php
- tests/test-single-site.php
Hello
Looks like there's a bug when loading ElasticPress (based on release 2.0) which results in a significant amount of unnecessary remote requests to the ElasticSearch server.
[`ep_loader`](https://github.com/10up/ElasticPress/blob/master/elasticpress.php#L53), hooked on `plugins_loaded`, instantiates a new EP_Settings regardless of need. This triggers a call to [`ep_check_host();`](https://github.com/10up/ElasticPress/blob/master/classes/class-ep-settings.php#L39) resulting the remote request to the ElasticSearch server.
It seems that EP_Settings should be limited to load only in admin. The class loads a handful of admin pages, along with this call to `ep_check_host();`
> Stop loading the EP_Settings class on the front end

- classes/class-ep-wp-query-integration.php
Adds a search scope filter before query generation.  Accepts `all` (string), a single site id (int or string), or an array of site ids (array).
Example usage:
```php
/**
* Global search of all the blogs in a network.
*/
function filter_ep_search_scope( $scope ) {
$scope = 'all';
return $scope;
}
add_filter( 'ep_search_scope', 'filter_ep_search_scope' );
```
> Add search scope filter. Closes #544

- classes/class-ep-modules.php
Currently modules run their setup callbacks on the `after_setup_theme` hook. I ran into an issue where I needed the setup callback to override some functionality another plugin was adding on the  `plugins_loaded` hook, which wasn't possible in the current setup.
So this changes the hook from `after_setup_theme` to `plugins_loaded`. I don't believe this will impact anything else but does make these setup callbacks run sooner, which should hopefully prevent any issues in the future with code not running in time.
> Change hook used to setup modules.

- classes/class-ep-api.php
- Important for searching unattached media (post_parent = 0)
- empty( $args['post_parent’]): returns true if $args['post_parent’] = 0
> Fixed: support post_parent = 0

- includes/mappings/5-0.php
This mapping seems to work for me. I tried to keep the `analyzer` parameter in the `sortable` field, but Elasticsearch doesn't like it. Not sure if there is an alternative. Perhaps the standard analyzer is sufficient?
> Potential mapping solution for #643

- classes/class-ep-api.php
In Wordpress v4.6 when get_sites() was introduced to replace `wp_get_sites()` the 'limit' argument parameter changed to `number`.  Without `number`, multisite installations will revert to only returning the first 100 sites. This update adds the `number` param to the `ep_indexable_sites_args()` filter to resolve this issue while maintaining backwards compatibility with `limit`.
Fixes #685
> Adds 'number' param to satisfy WP v4.6+. Fixes #685

- bin/wp-cli.php
Right now, `wp elasticpress stop_the_insanity` is available for use, which wasn't the intention.
> Stop the insanity should be private

- features/woocommerce/woocommerce.php
After further testing I found an oversight in my previous PR.
The `$query->query-vars['ep_integrate']` value has not been set at this point, so the `ep_elasticpress_enabled` function will always return false unless explicitly enabled by the `ep_elasticpress_enabled` filter.
> Removed ep_elasticpress_enabled check.

- features/search/search.php
First pass at fixing the date decay issue. Currently, date decay is completely usurping relevancy scores and taking otherwise perfect matches to relevancy of zero because they are too far away from the decay origin. By adding score_mode of avg, a relevancy score is calculated using a weighted average which is preferable since we have large boost values for some parts of the query. We want to maintain that. By setting boost_mode to sum, the scores are added instead of the default multiply which seems to have been the primary driver of lowering relevancy scores to zero.
> Date Decay Fix – First Pass

- features/woocommerce/woocommerce.php
Woocommerce product search default order is 'ASC'. We want it to be 'DESC'. Fixed #737
> Fix woocommerce product search default order

- classes/class-ep-api.php
- readme.txt
This should fix #749.
Apparently on some ES hosts, the plugins endpoint is restricted. This PR will default to the root endpoint if the plugins one is unavailable.
> Fallback to different endpoint if plugins endpoint is unavailable

- features/woocommerce/woocommerce.php
The source of the problem is from the WC_Query:
https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-query.php#L453-L483
if there is no querystring orderby then it fall back to the default settings.
But it set the orderby to menu_order title in line https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-query.php#L449
We can only check from the meta_key, and translate that into correct orderby
Fixed #745
> make sure the orderby is correct for default sorting

- classes/class-ep-dashboard.php
If the Elasticsearch server gone away or return error while dashboard sync.
Stop the sync immediately, show error message.
Fixed #762
> better error handling while dashboard sync error

- classes/class-ep-config.php
In order to leverage the full capabilities of wildcard permissions offered by X-Pack, it is required to be able to set a unique index prefix that is applied to all indexes.
This PR allows developers to define a constant in wp-config.php that will add a prefix to their index and alias names without the need to use filters.
`define( 'EP_INDEX_PREFIX', 'abc-' );`
> Index Prefixing Constant

- includes/mappings/5-0.php
Adds a mapping parameter for ES 5.0 to allow for the adjustment of the total_field_limit value that was introduced in ES 5.x (https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_mapping_changes.html)  If you look for "Field Mapping Limit's" on that page you will see the change.
> Mapping for ES 5 for total_field_limit

- classes/class-ep-api.php
Added a more detailed explanation of what is going on with the `posts_per_page` conversion and added the option to alter the max results window size hardcoded in EP.
You might be wondering: "Hey, why do we need this?" – well, it is basically documentation with the added functionality of increasing/decreasing the size so you can optimise it for your own server (some might have cheaper ES instances where the window size have been reduced etc.).
> Add filter for max results window size

- features/woocommerce/woocommerce.php
It is currently not possible to filter by product type in the backend. This PR should solve that by adding `product_type` taxonomy support by default.
> Add default support for "product_type" (Woo)

- features/woocommerce/woocommerce.php
It might be useful to automate the product taxonomies but, for now, I would love to see support for "custom taxonomies" for the WooCommerce feature.
The reason is that custom taxonomies added to "products" by plugins are not sortable in the admin view if they are not added to the `$supported_taxonomies` array.
> Add support for custom taxonomies in WooCommerce

- README.md
- classes/class-ep-dashboard.php
- classes/class-ep-feature.php
- elasticpress.php
- includes/header.php
Dashboard sync can be disabled by defining the constant `EP_DASHBOARD_SYNC` as `false` in your wp-config.php file.
```php
define( 'EP_DASHBOARD_SYNC', false );
```
* This can be helpful for managed sites where users initiating a sync from the dashboard could potentially cause issues such as deleting the index and limiting this control to WP-CLI is preferred.
* When disabled, features that would require reindexing are also prevented from being enabled/disabled from the dashboard.
When `EP_DASHBOARD_SYNC` is defined as `false`:
* Attempting to manually trigger a dashboard sync via `admin.php?page=elasticpress&do_sync` will not initiate a sync. This is to prevent any tomfoolery, intentional or otherwise.
* The `resume`, `pause` and `stop` buttons are not disabled by this constant. This is to …
> Disable dashboard sync with constant. Closes #701

- classes/class-ep-api.php
This fixes an issue when Elasticsearch returns empty results for a given query.
Here is the original response of Elasticserch 5.2.2
```json
{"took":5,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}
```
> Add new condition to determine whether results are empty or not.

- classes/class-ep-wp-query-integration.php
Do not modify original SELECT FOUND_ROWS(); MySQL query when Elasticsearch query failed.
> (Closes #825) Incorrect posts_found variable when Elasticsearch query is not successful

- features/woocommerce/woocommerce.php
WC_Order::get_id() only available in WooCoommerce >= 3.0.0
since we know that the order id is equal with $search_key_safe, let's just use it. so we don't have backward compatibility issue
> fix error for old woocommerce version

- features/woocommerce/woocommerce.php
Mentioned in #811, ElasticPress returns the wrong product when being previewed. This PR simply checks to see if the `preview` query string is set and then prevents the search to be run on Elasticsearch.
> If a WC draft is being previewed, do not use Elasticsearch.

- includes/mappings/pre-5-0.php
Note: Github added a new line at the end automatically since this should be the default.
> Fixed wrong ES version in doc block.

- .github/ISSUE_TEMPLATE.md
Let's standardize when the user open an issue.
I create a issue template, so we can easily replicate the issue.
Read more: https://help.github.com/articles/creating-an-issue-template-for-your-repository/
> add github issue template for easier tracking issue

- classes/class-ep-api.php
This fixes #863.
Save request results in a transient. This will unfortunately cause the user to have to wait 5 minutes to be shown a dashboard notification if their ES goes down or plugins change.
> Cache Plugins Request for 5 Minutes

- elasticpress.php
- tests/test-admin-notifications.php
The wrong variable is being set in the version reindexing notice checker. This fixes that plus adds tests.
> Version Reindexing Notice is Not Appearing

- .travis.yml
This PR will create two additional builds in Travis to test out Elasticsearch 5.0 and 5.2.
> TravisCI - support multiple ES versions (5.0 and 5.2)

- classes/class-ep-api.php
- includes/mappings/5-0.php
- includes/mappings/5-2.php
By adding a normalizer in the 5.0 mappings for sortable fields, the case-sensitivity issue is resolved. This results in five out of the six failing unit tests to pass. 
(The testSearchPostDateOrderbyQuery test is only returning two results instead of three. I'm not sure if this is because the post_title is `ordertes` instead of `ordertest`.)
@tlovett1 and @ivankristianto can you take a look at this to verify if this resolves the issue or if this has the potential to cause different issues to occur.
Edit: The normalizer was introduced in 5.2, so I have added a 5.2 mapping for backwards compatibility.
> Normalizer for sortable fields

- classes/class-ep-api.php
- tests/test-single-site.php
This PR will allow taxonomies that are not public to still be queryable.
> Index Taxonomies that have publicly_queryable as true

- classes/class-ep-api.php
- classes/class-ep-wp-query-integration.php
- features/search/search.php
- features/woocommerce/woocommerce.php
Support the two `WP_Query` fields cases that are supported in core.
You can read more about my rant of why/how/thoughts in the open issue: #724 
_**NB**: I have not written any tests and I am not sure that I have covered all cases in the different modules (ex `WooCommerce`) - but I have manually tested it on regular searches on a vanilla Woo install with `storefront` theme and dummy data._
/ Kallehauge
> Add WP_Query fields support

- classes/class-ep-api.php
This was left around for backwards compat. It caused issues for people since it doubled the size of meta stored in ES.
@ivankristianto can you test?
> Remove post_meta key from ES post object

- features/woocommerce/woocommerce.php
Add "Product shipping class" taxonomy to list of supported WooCommerce taxonomies.
The links to see all products with a specific shipping class at "WooCommerce > Settings > Shipping > Shipping classes" currently link to "broken lists" since we do not whitelist the shipping class taxonomy in the WooCommerce feature.
It is possible with `ep_woocommerce_supported_taxonomies` to add it but I feel like it should be there "natively".
_There might be some follow-up work to be done when the following issue gets answered/fixed in WooCommerce itself: https://github.com/woocommerce/woocommerce/issues/16435. If I manually provide the `&post_status=publish` in the URL, I still get some unexpected results. But at least it mimics the current status quo in WooCommerce, so I feel like it is ready to be …
> Add shipping class tax to supported taxonomies

- classes/class-ep-dashboard.php
Example case:
Using Elasticsearch >5.3. Confirmed working. EP outputs a notice that cannot be suppressed. I want to suppress for all users.
> Add filter on the admin notices to more granularly control them.

- features/woocommerce/woocommerce.php
This fixes these notices:
`PHP Notice:  Undefined index: post_type in elasticpress/features/woocommerce/woocommerce.php on line 567`
> Fix WC post type warnings

- classes/class-ep-api.php
This is safer way to check the property we want from the $taxonomy object.
> Check taxonomy object has the property fixed #881

- features/woocommerce/woocommerce.php
Products on orders are, by default, searchable by name on the orders overview page in the admin interface. This PR is an easy way to support the same functionality out of the box and 90% mimics the way WooCommerce currently does (from my understanding).
> WooCommerce order products search

- features/woocommerce/woocommerce.php
@tlovett1 This fixes as issue introduced in https://github.com/10up/ElasticPress/pull/917. https://github.com/10up/ElasticPress/pull/917 doesn't work with WooCommerce 2.x that doesn't use  `WC_Order_Item_Product` as `$product_item` but raw array.
> Fix sync error when WooCommerce 2.x installed

- features/woocommerce/woocommerce.php
@tlovett1,
This is a fix for #943 - I couldn't reproduce this on my local however it's possible that functions `get_term_by` and `get_term` may not return valid data as expected. Adding extra sanity checks before accessing their results won't do any harm.
> Add sanity checks before accessing object properties

- README.md
- classes/class-ep-api.php
- tests/test-single-site.php
This adds support for `and` of the tax array `operator` parameter. This will now work:
```php
new WP_Query( [
'tax_query' => [
[
'taxonomy' => 'test',
'field' => 'slug',
'terms' => [ 'test1', 'test2' ]
'operator' => 'and',
]
]
] );
```
> Support inner tax query array and operator

- features/documents/documents.php
@tlovett1 In one place we use short array syntax that was introduced in PHP 5.4. WordPress still supports PHP 5.2.4+ so I believe that our plugin should also be PHP 5.2 and 5.3 compatible.
> Use PHP 5.2 compatible array syntax

- bin/wp-cli.php
This PR adjusts the values that wp-cli reports to the end-user when `wp elasticpress stats` is issued. The original version was using the 'total' value which reports the number of documents multiplied by the number of replicas that exist for the given index inflating the number. By default, Elasticsearch uses 5 shards and 2 replicas meaning number of documents is twice the expected value. The PR uses the 'primaries' value which reports the actual number of documents in the index. 
It also adjusts the output so that both the size of the indexed documents is reported as well as the total size of the index including all of the replicas.
> Stats reported by wp-cli are incorrect

- features/woocommerce/woocommerce.php
It is currently possible to trigger the WooCommerce feature's arguments translation on single post/product queries which can cause trouble for some projects. One of the problems I've experienced is that the page should be triggered as a 404 page, since the requested product doesn't exist, but instead returns a HTTP 200 with results (I'm guess that the result varies depending on the individual theme - but I have experienced that I get a collection of products).
Example of Woo URL that can cause this issue: https://example.com/?post_type=product&p=12341234
The URL example satisfies the WooCommerce feature's single condition by not containing a `product` query_var.
> Harden the "Is single" check in WooCommerce feature

- bin/wp-cli.php
This pull request implements a `--post-ids` CLI option to index only specific posts, as described in 
issue 886.
Example usage:
`$ wp elasticpress index --post-ids=52,51`
> Implement --post-ids CLI option to index only specific posts

- includes/settings-page.php
Principle of least privilege: WordPress admin users don't need to know
this.
---
In our case, we host WP sites. The clients who use them shouldn't know the username, password, and hostname of the Elasticsearch instance.
Great plugin by the way. Thanks.
> Hide EP_HOST value on settings page

- features/woocommerce/woocommerce.php
@tlovett1 This is fix for #938 when duplicated Elasticsearch queries are made on WooCommerce (2.x only) orders page. Yoast is calling global `$wp_query->get_posts()` that tries to run ES query again. First thing that it is abundant as there is no point in making the same query again. The second issue is that first `$wp_query->get_posts()` call sets up `$_GLOBAL['post']` object to first post from ES response and this forces all calls to `get_post()` to return this post always (even if `get_post()` is called with numeric parameter).  Duplicated `$wp_query->get_posts()` makes `ep_wc_search_order` (action hook for `parse_query` action) to incorrectly execute following logic:
```php
$search_key_safe = str_replace( array( 'Order #', '#' ), '', wc_clean( $_GET['s'] ) );
$order = wc_get_order( …
```
> Disallow duplicated Elasticsearch requests on WooCommerce Orders page

- features/woocommerce/woocommerce.php
By default, WooCommerce searches include `author_name`. This PR will remove that search field.
Fixes #1086
> Remove author_name from WooCommerce searches

- classes/class-ep-api.php
This PR adds post meta to posts that are password protected. It then alters the public query to ElasticSearch by checking against this meta value to prevent password protected posts from appear in search results.
This approach seemed to be the least intrusive as I did not want to alter mappings or prevent the post from being indexed completely, which would not allow it to show in the WP admin if protected content is activated.
This PR fixes #1083
> Exclude password protected posts in search results. 

- features/autosuggest/autosuggest.php
Developers will be able to define a constant in wp-config.php to their autosuggest endpoint. The new constant is called EP_AUTOSUGGEST_ENDPOINT.
Resolves #1033
> Allow developers to specify a constant to their autosuggest endpoint

- classes/class-ep-api.php
Hi @allan23 ,
Could you please use this PR which solves #1153 ?
Previously the $comment_status was set to 0 while applying `absint()`. Now, it gets either an open / closed status which is what it should. 
Thanks!
> Do not apply absint to comment_status

- features/related-posts/related-posts.php
- tests/features/test-related-posts.php
Hi @brandwaffle , @allan23 ,
When you have some time, could you please check this PR which fixes the related post feature? This  seems to be broken since ElasticSearch 6.0 and above.
Currently, a 400 error happens and you get this response when using the ElasticPress debug bar :
```
{
"error": {
"root_cause": [
{
"type": "parsing_exception",
"reason": "[mlt] query does not support [ids]",
"line": 1,
"col": 93
}
],
"type": "parsing_exception",
"reason": "[mlt] query does not support [ids]",
"line": 1,
"col": 93
},
"status": 400
}
```
The feature is broken due to a change in the way MLT (more like this) is structured in ElasticSearch: 
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html and in my testing, this happens since version 6.0 . I tested 6.4, …
> Add compatibility for new MLT structure

- bin/wp-cli.php
- classes/class-ep-dashboard.php
We currently query for all fields, but I don't think this is necessary since we call `get_post( $post_id )` within the `queue_post()` function.
Changing the query to only query for IDs significantly improves the indexing time.
Testing locally with 5,833 documents the index time was an average of 90 seconds. Applying this patch lowered it to around 24 seconds.
Working on a bigger ElasticSearch instance with 819, 362 documents we can now index in about 2.5 hours, previously it took almost triple that. This was using AWS `t2.small.elasticsearch` instance.
> Only query for post IDs when indexing posts

- features/woocommerce/woocommerce.php
Hi @brandwaffle, @allan23 
Could you use  this PR which addresses #906 ?
As noted by the OP, feature woocomerce sets the order to relevance overriding https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L1523 
By removing these lines, product queries can be sorted now by rand.
Thanks
> Let WC feature order by rand.

- classes/class-ep-config.php
We use the `ep_index_name` to hot index. If we ever need to reindex a large site we don't want to delete the index and start using mysql until the new index is ready. This works really well by using this filter and adding a suffix to our index name for the current index version. We don't update the version until the new index is ready and then the front end will start using it.
We want to be able to do a similar thing to ep_host. We are currently running v2.1 of EP and 2.3 ES on a large multisite. We want to be able to spin up a non web traffic box where we can override the `ep_host`. This will allow us to index all of our sites on the new elastic search instance behind the scenes and when the index is ready we can change our `EP_HOST` so it's now using the new instance.
> Add apply_filters to ep_host.

- classes/class-ep-config.php
Fix `is_indexing_wpcli` method to check for `ep_wpcli_sync` instead of `ep_index_meta`
> ep_is_indexing_wpcli is returning true when WP-CLI index is running

- features/woocommerce/woocommerce.php
Hi @allan23 ,
Could you please check this PR which addresses #1134 ?
This sets the order and orderby from `$query->query_vars['order']` and `$query->query_vars['orderby']` in case the `GET` param was not set. This comes handy on certain scenarios, for example when setting the sort option from the customizer.
Steps to reproduce issue:
1.- Have some products with different categories.
2.- From the customizer (latest version of woocommerce) go to woocommerce->product_catalog and set `shop page display` to `show categories` and `default sort pricing` to by `price asc` or `desc`. 
3.- Hit publish and visit a category.
4.- See a 400 error in the debug bar.
Thanks
> Set orderby and order by price from query_vars

- classes/class-ep-api.php
Hi @allan23 , @tott ,
Could you please review this PR which addresses #1127 ?
The compare like query was previously defined as: 
case 'like':
if ( isset( $single_meta_query['value'] ) ) {
$terms_obj = array(
'query' => array(
'match' => array(
$meta_key_path => $single_meta_query['value'],
)
),
);
}
break;
However we can't make a query within a filter query context. We can however use a type of a query inside post_filter to filter out results. 
Since compare-> like is defined like this: 
https://github.com/WordPress/WordPress/blob/df0958697a5d897a15ea78d37a001e2f3752875f/wp-includes/class-wp-meta-query.php#L595
I think we could mimic the same behavior by using a wildcard query : 
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html
I've tested this …
> Use wildcard query with compare like.

- features/protected-content/protected-content.php
Hi @allan23 , @brandwaffle ,
Could you please use this PR which addresses issue #1133 ?
This commit sets a parameter when calling `get_post_types()` to get all non public post_types, and merges them with the previously filtered post_types in `ep_indexable_post_types ` , in case post_types were filtered before` ep_pc_post_types()`. Probably `array_unique()` is not needed anymore, but happy to read your feedback.
Thanks!
> Filter prefiltered post_types when protected content feature enabled.

- includes/settings-page.php
Hi @tott and @allan23 ,
Could you please review this PR which fixes #1202  ?
This PR hides the trailing dash for the EP_PREFIX ( Subscription ID ) on the settings page.
Thank you.
> Hide prefix trailing dash on settings page

- features/protected-content/protected-content.php
@tlovett1 this is enhancement for https://github.com/10up/ElasticPress/issues/883.
@ivankristianto suggested three enhancements however I am not sure if we need/should implement all of them.
Removing weighting results by recency should be definitely added for admin queries (that's why I put it in _Protected Content_ feature). I don't think we should always sort by __score_ as we will override admin pages sorting feature (when clicked on a sortable column). If there is no sorting set on edit.php page then __score_ sorting is used by default.
Last @ivankristianto suggestion about adding _min_score_ sounds quite promising however we would need to find some correct number and this may be very personal preference. I wouldn't add _min_score_ unless we have some idea about its value that could …
> Remove weighting by date in admin

- features/woocommerce/woocommerce.php
Hi @allan23 ,
Could you please check this pull request which addresses #1137 ?
As noted by the OP in the issue, `$search_fields['meta'] = array( '_sku' );}` is overriding custom meta search fields.
By using his suggestion, we make sure the `_sku` field is still searchable.
Thanks!
> Do not override custom fields on wc search.

- classes/class-ep-api.php
Hi @allan23 ,
This PR replaces the use of wildcard query for a match_phrase. This way, we account for queries that are not a pattern.
Thank you,
> Use match_phrase as alternative for wildcard

- classes/class-ep-config.php
- classes/class-ep-dashboard.php
- includes/settings-page.php
Hi @allan23 ,
Could you please review this PR which adds feature #1179 ?
This PR adds a field  on the settings page if `ep_host` is set and filter `ep_index_posts_per_page` has no callback function: 
I've tested this works on single and multisite.
Please let me know your thoughts. 
Thanks!
> Allow user to set bulk settings

- classes/class-ep-dashboard.php
- features/autosuggest/autosuggest.php
Hi @tott , @allan23 ,
Could you please review this PR which addresses #1205 ?
This adds a dismiss  notice when autosuggest feature is enabled and is using plugin defaults: 
As well as a radio button to switch between using defaults and safe post_type values `post`, `page` and post status `publish` : 
Thank you!
> Default autosuggest to plugin settings.

- classes/class-ep-dashboard.php
While working on a client project, I ran into the following notice: 
`Notice: Trying to get property 'title' of non-object in /var/www/html/wp-content/plugins/elasticpress/classes/class-ep-dashboard.php on line 358`
Seemed to only happen when switching branches on the client's project though. Since `ep_get_registered_feature()` can return a **false** value, this PR adds an `is_object()` check before accessing the title property on the object.
> added is_object() check for auto-activate-sync notice

- features/autosuggest/autosuggest.php
Hi @allan23 ,
Can you please review these changes that address #1231 ?
I found the localized post type/status variables where taken as an object instead of a array when plugin defaults is enabled. Also, I swapped post type for status and vice-versa when using plugin defaults, which was causing this to fail on safe values.
Thanks!
> Convert indexables to non-associative array

- classes/class-ep-api.php
Issue: ElasticPress Failed To Index if Post Have Null for Meta Key #1240
> Skip post meta for index if meta key empty/false.

- classes/class-ep-config.php
- classes/class-ep-dashboard.php
Hi @allan23 ,
Can you please review this PR ?
This adds a new function to first convert the bulk settings input into a integer, then check if the value is 0 or empty, as this can sometimes be the result of converting into an integer : http://php.net/manual/en/language.types.string.php#language.types.string.conversion
If it is empty or 0, then set bulk settings to default of 350.
This was being problematic as `register_setting()` was submitting an empty string the first time a user sets his elasticsearch host, hence the option was getting updated and ended up getting converted to 0.
Thanks!
> Do not allow 0 to be set as bulk settings

- includes/classes/Feature/Autosuggest/Autosuggest.php
Fixes issue with reversed post_status and post_types in Autosuggest.
Fixes passing only array_values to resolve the error in #1272
> Fix autosuggest in 3.0 (resolves #1272)

- assets/js/autosuggest.js
- includes/classes/Feature/Autosuggest/Autosuggest.php
Hi @allan23 , can you please review this PR which addresses #1233 ?
This should add the ability to add autosuggest on elements/selectors that have been defined in the autosuggest settings. I tried it with custom selectors `.search-box, #search-test, input[type=text]` and so far they work for me. 
Thanks!
> Redo: Add ability to define autosuggest selector

- includes/classes/Indexable.php
- Static value might interfere 32-bit signed integers as the max value is `2,147,483,647`, while for 64-bit it's `9,223,372,036,854,775,807`.
- Avoid conflicts between 32- and 64-bit.
- Use predefined PHP constant to output the maximum integer value depending on the system.
- Was there an intention by use the static value instead of the constant?
> Changed max int to use core predefined constant.

- includes/classes/Indexable/Post/SyncManager.php
v2 passes $post_id as the 3rd argument. This also prevents a fatal for existing filters that expect 3 arguments to be passed.
v2 implementation
https://github.com/10up/ElasticPress/blob/ca929db2869576b5e1975436eda4d21f150e50b3/classes/class-ep-sync-manager.php#L268
Updates to v3 from v2 won't trigger a fatal error for common `ep_post_sync_kill` filter usage.
Developer/maintainer may not be aware of the change to this filter.
Resolves #1351
> Pass $post_id twice in ep_post_sync_kill for backwards compatibility

- includes/classes/Indexable/User/User.php
- includes/mappings/user/pre-5-0.php
Currently, ElasticPress supports Elasticsearch 1.7. However, user mapping is not compatible with the earlier versions due to `text` and `keyword` support. – https://www.elastic.co/blog/strings-are-dead-long-live-strings 
In these changes, backporting user mapping with `string` type.  
Supporting user search to existing Elasticpress setups without worry about the version.
Probably, we don't want to maintain the mapping for legacy setups. Instead, we can update the related part of the documentation. (User feature requires WordPress 5.1+ and Elasticsearch 5.0+) 
run `wp elasticpress index --setup` with the earlier versions of Elasticsearch (5.0 <)
> make user mapping compatible with earlier versions than 5.0

- includes/classes/Indexable/Post/Post.php
- tests/indexables/TestPost.php
Currently, when building out taxonomy query information to send to elasticsearch, we only account for a single level of nesting. But WordPress supports taxonomy queries that are nested, so that information ends up being lost and the query results don't match what we want.
This PR fixes that by recursively looping through the passed in `tax_query` information. This ensures that we process all levels of nesting that may exist. The majority of the code here is the same as before, as far as building out the query. I've added the recursive looping and changed slightly how we set this tax query information in our main elasticsearch query.
Nested tax queries currently do not work, so adding this feature brings us closer in line to the core functionality WordPress supports
Logic to build out the …
> Add support for nested taxonomy queries

- includes/classes/Feature/WooCommerce/WooCommerce.php
This PR fixes #1376 by checking the orderby param of the query and if it is `popularity` rewrites it to `meta.total_sales.long date ` to sort in Elasticsearch when popularity is set as the default sorting from the customizer
1.- Set a woocommerce theme like storefront
2.- On the frontend, go to customize->woocommerce->product catalog->Default product sorting and select popularity as sorting default
3.- Refresh and check status in debug bar/query body/results
- [] My change requires a change to the documentation.
> Fixes 400 error when popularity is default sorting

- includes/classes/Feature/Facets/Facets.php
- includes/classes/Feature/Facets/Widget.php
- includes/classes/Feature/WooCommerce/WooCommerce.php
This PR allows WooCommerce product attributes to be facetable in 3.0. The initial implementation of attribute facets (in 2.8) caused a bug where attributes were disabled on product category pages.
> Product attribute facets for 3.0.

- includes/classes/Feature/Facets/Facets.php
- includes/classes/Feature/WooCommerce/WooCommerce.php
- Also fixed linting errors and removed unnecessary 2nd argument from the `apply_filters` function
- The changes introduced in #1344 contained functional and code style issues as stated in my comment in the related PR
- This PR queries the WC attribute taxonomies to fulfil the requirements of the foreach when trying to access the label and name property of the taxonomy object
- Also fixes the code style
- As stated in my comment, another solution would have been to return names/slugs only which would probably more inconvenient for the users 
- Get it working :-)
- Performance issues due to return the objects instead of DB queried strings
- Insert Facet widget
- Select product attribute
- Check if ES query also contains the slug entry as added in …
> Fixed Facet widget does not render WC product attribute options.

- includes/classes/Command.php
`WP_CLI::error` calls exit by default so the syncing transient isn't deleted. This fixes that.
> Delete wpcli sync option/transient when an error occurs

- includes/classes/Command.php
- includes/classes/Elasticsearch.php
- includes/classes/Indexable/Post/SyncManager.php
Currently when a new site is created within a network the mappings are not sent so no index exists. When the first index happens ElasticSearch will create the index for us, but without the correct mappings - this also means the network alias isn't created, preventing the site from being visible in the global index.
This PR addresses two issues -
- Creates mapping once a new site is created within a multisite and creates the network alias
- Fixes fatal error when using the `recreate-network-alias` command
Note: Using the hook `wp_insert_site` seemed too early and didn't give me the index name therefore using `wp_initialize_site` instead.
New sites will have correct mapping and will be searchable within the network index.
None - but this fix doesn't address old sites. Site admins will need …
> Ensure new sites within multisite have the correct mappings and global alias

- includes/classes/Indexable/Post/SyncManager.php
- includes/classes/Indexable/User/SyncManager.php
- includes/classes/SyncManager.php
- tests/indexables/TestUser.php
Adding possibility to trigger sync whenever a limit of objects in the queue is reached.
This is sometimes useful when during one page load a lot of content is
updated (ie. during programatic content imports).
In these cases it's possible that if the import process fails due to a
SIGKILL or SIGTERM signal the queued up changes will not be synced and a
full reindex is required.
In order to activate this feature a define needs to be set in
wp-config.php or similar suitable place.
```define( 'EP_SYNC_CHUNK_LIMIT', <max_amount_of_objects_in_queue> );```
Additionally this change implements a add_to_queue() method in the sync
manager allowing an action to fire whenever an object is added to the
queue.
```do_action( 'ep_after_add_to_queue', $object_id, $this->sync_queue);```
> Provide option to sync prior to shutdown

- includes/classes/Indexable/Post/Post.php
Proposed change to prepare_meta() method allows modification of post meta data so that virtual/dynamic meta data could be inserted into ElasticSearch even though the data itself technically is not available as post meta data for that object.
e.g. inserting dynamically created product code / SKU.
No alternatives were considered. Open to ideas.
Possibility to insert custom meta data. Use cases may vary, my primary goal autosuggest improvements.
New filter might be misued by 3rd party developers where use of existing filters (`ep_prepare_meta_allowed_protected_keys`, `ep_prepare_meta_excluded_public_keys` and `ep_prepare_meta_whitelist_key`) could be more efficient .
Ran sync processes with and without additional filters to insert "virtual" meta data. Confirmed data to be indexed as …
> Adding filter to modify post meta data.

- includes/classes/Feature/RelatedPosts/RelatedPosts.php
Prevents unnecessary adding of sticky posts to related posts
This is a fix for issue #1323.
My related posts returned well over a thousand when I asked for 3.  After adding the "add_sticky_posts" argument, it properly returned the number of posts I asked the method to retrieve.
> Add "ignore_sticky_posts" argument to find_related() method

- includes/classes/Feature/Facets/Facets.php
Uses correct `pa_` prefixed taxonomy name for product attributes.
#1444
> Use proper taxonomy name for WC attributes. Fixes #1444

- includes/classes/Feature/WooCommerce/WooCommerce.php
Dynamically adds all product attribute taxonomies that exist to the supported taxonomies in EP rather than supporting a small hardcoded subset.
#1447 
Fix issue where all products show up on a product attribute archive instead of just products that have the attribute.
> Fix product attribute archives

- tests/bootstrap.php
Fixes number of shards during tests. Unbreaks put_mapping, which allows tests to complete as normal
> Fix how number of shards are set during tests to not fail put_mapping

- includes/classes/Indexable/Post/Post.php
- includes/classes/Indexable/User/User.php
orderby is set to 'id' but 'id' is not a valid orderby type. The inline docs state...
```
*     @type string|array $orderby                 Sort retrieved posts by parameter. One or more options may be
*                                                 passed. To use 'meta_value', or 'meta_value_num',
*                                                 'meta_key=keyname' must be also be defined. To sort by a
*                                                 specific `$meta_query` clause, use that clause's array key.
*                                                 Accepts 'none', 'name', 'author', 'date', 'title',
*                                                 'modified', 'menu_order', 'parent', 'ID', 'rand',
*                                                 'relevance', 'RAND(x)' (where …
```
> id is not a valid order by value

- includes/classes/AdminNotices.php
Fixes issue when comparing a version with a single part (5) to a version with 2 (5.0) - normalizes the version to x.0 when it only has one segment.
> Fixes version compare bug

- includes/classes/Feature/Facets/Facets.php
Also accounts for WC not being activated at all).
Only uses WC attribute taxonomy name on actual WC taxonomies. Also completely ignores this if WC isn't activated.
Tested with and without Woocommerce activated with standard (non-attribute) taxonomies as well as woocommerce attributes on both ElasticPress facet widget and Woocommerce widgets.
Fixes #1457
Fixes error in facet widget when WooCommerce deactivated.
> Don't try and use wc_attribute_taxonomy_name on non WC Taxonomies

- includes/classes/Indexable/Post/Post.php
- includes/classes/Indexable/User/User.php
This PR changes `.value` to `.raw` when sorting by `meta_value`. The [Elasticsearch docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-fields.html#CO302-1) state that `.raw` is used for sorting and aggregations.
> Use .raw for sorting and aggregations

- includes/classes/Feature/Facets/Facets.php
Verify the expected aggregations exists in the EP response before adding them to `$GLOBALS['ep_facet_aggs'] `. I'm working on a project that uses custom aggregation and `$response['aggregations']['terms']` was not always present in the EP response.
N/A
Prevent the following PHP warning from being thrown:
Warning: Invalid argument supplied for foreach() in /var/www/html/wp-content/plugins/elasticpress/includes/classes/Feature/Facets/Facets.php on line 294
None that I'm aware of.
I made the same change in the EP plugin on the site and confirmed the warning was no longer thrown. I did not see any negative side effects.
- [ **Where is this doc?** ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ **I really tried, but I couldn't get the tests working :(** ] All new and …
> Verify expected facet aggs

- includes/classes/Indexable/Post/Post.php
The `author_name` query var is meant to use the [user nicename](https://developer.wordpress.org/reference/classes/wp_query/#author-parameters). 
Currently the Post indexable is setting this value to the display_name. This means we can't search using this field without altering the query via the `ep_formatted_args` hook.
I currently have this code in place to force the code to work as expected, but it will need to loop twice over the args to ensure that the indexes for both `post_filter` and `aggs` are the same. I assume they are, but I would also not be surprised if they weren't.
```
function set_search_args( $formatted_args, $args ) {
if ( ! empty( $args['s'] ) && ! empty( $args['author_name'] ) ) {
foreach ( $formatted_args['post_filter']['bool']['must'] as $i => $filter ) {
if ( isset( …
```
> fix incorrect author_name usage.

- .github/workflows/push-deploy.yml
They said yesterday they'd fix it "this week", guess they got to it quickly so the last tag failed to deploy. See https://github.community/t5/GitHub-API-Development-and/How-to-restrict-execution-of-GitHub-Actions-workflow-on-tags/m-p/29640#M2671
> Update to new tag filtering for GH Actions

- includes/classes/Feature/RelatedPosts/RelatedPosts.php
Ensure block assets are only enqueued when the block editor is loaded. 
Fixes https://github.com/10up/ElasticPress/issues/1505.
* Hook block asset enqueue callback on `enqueue_block_editor_assets` instead of `init`
* Avoid potential conflicts or loading assets in WP < 5.0.
> Improve block asset enqueueing: hook on `enqueue_block_editor_assets`

- includes/classes/Feature/WooCommerce/WooCommerce.php
Allow user to set `meta` and `taxonomies` search fields in WooCommerce product search per #1522.
> Don't overwrite search_fields

- includes/classes/Feature/Autosuggest/Autosuggest.php
Hotfix to address issue reported in #1560 
Just ensure to pass proper priority when removing filter.
> Ensure removal of filter with proper priority.

- CHANGELOG.md
- elasticpress.php
- readme.txt
1### Description of the Change
Under some conditions the data object returned for the autosuggest query can include results and could get big if matching documents are larger files. This change ensures that returned body object is not cached.
> Prep 3.2.6 release

- includes/classes/Elasticsearch.php
- includes/classes/Feature/Facets/Facets.php
- includes/classes/Indexable.php
- includes/classes/Indexable/Post/QueryIntegration.php
- includes/classes/Indexable/User/QueryIntegration.php
This fixes the problem addressed in #1575. Before saving aggs, we make sure we are getting the aggs from the main query.
> Pass query object to EP response so we can check for main query

- includes/partials/settings-page.php
Instead of showing ES version for .IO, we will just show Managed Platform as the .IO platform has customizations that make it unique from the core software.
> Show managed platform message instead of ES version for EP.io

- includes/classes/AdminNotices.php
Never show ES version warning on .IO.
> Never show ES version warning on .IO

- includes/classes/Indexable/Post/Post.php
This fixes search for bbPress. We make sure the post type array doesn't have keys.
> Make sure post type array doesn't have keys

- includes/classes/Feature/Facets/Facets.php
Fixes a bug where faceting was ignoring `ep_integrate`.
Add `ep_integrate` false to main query, turn faceting on. Faceting should not work.
> When ep_integrate set to false, do not apply faceting. Closes #1589

- includes/classes/Feature/Documents/Documents.php
- includes/classes/Feature/SearchOrdering/SearchOrdering.php
{"message":"Invalid argument supplied for foreach()","context":{"exception":{"class":"ErrorException","message":"Invalid argument supplied for foreach()","code":0,"file":"/var/www/html/pdinfo/releases/20190829162419/web/app/plugins/elasticpress/includes/classes/Feature/SearchOrdering/SearchOrdering.php:743"}
It is possible for the pointers variable in function handle_post_trash to be empty. This is generally not an issue unless running a very strict policy of not allowing any Errors. Our use case requires that we verify that variables being manipulated are verified as not empty.
Please consider accepting this change.
Elasticpress can attempt to manipulate an empty variable that it expected to be an array. This change will prevent this manipulation from happening and prevent an exception. …
> error_fix(SearchOrdering.php) - Invalid Argument

- includes/classes/Elasticsearch.php
We can receive top X hits for each post_type with just one ES request. The searched hits are placed in this case not in $result['hits']['hits'] but deep in $result['aggregations'][...]...[...]['hits']['hits']
s. https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-top-hits-aggregation.html
> added filter to flatten hits that are come within aggregations.

- includes/mappings/post/7-0.php
- includes/mappings/user/7-0.php
Requirements:
ES 7.5
Problem:
YYYY refers to a week based year and does not work
Error Log:
```
- 10796 (Post): 
type: mapper_parsing_exception
reason: failed to parse field [post_date] of type [date] in document with id '10796'. Preview of field's value: '2012-02-29 23:00:00'
type: date_time_exception
reason: Invalid date 'February 29' as '1970' is not a leap year
- 7860 (Post): 
type: mapper_parsing_exception
reason: failed to parse field [post_date] of type [date] in document with id '7860'. Preview of field's value: '2016-02-29 00:00:00'
type: date_time_exception
reason: Invalid date 'February 29' as '1970' is not a leap year
```
see [disqus on ES](https://discuss.elastic.co/t/type-date-time-exception-reason-invalid-date-february-29-as-1970-is-not-a-leap-year/205570)
> ES 7 fix: documents with leapyear-02-29 00:00:00 cannot be indexed

- .gitignore
- docs/development.md
- includes/classes/Indexable/User/QueryIntegration.php
- tests/php/TestUtils.php
- tests/php/indexables/TestUser.php
- Added `testSanitizeCredentials()` to help me get up to speed on EP unit tests and additional examples to the development documentation.
- Updated `maybe_filter_query()` for WP_User_Query to handle a single field and multiple fields as an array.
- Added unit tests `testSingleUserFieldQuery()` and `testMultipleUserFieldsQuery()`
User queries with 'fields' will now work correctly.
None
Created unit tests for the updated functionality.
Fixes #1609 
- Fixed bug where passing 'fields' to WP_User_Query was not returning the requested fields
> Fixes for WP_User_Query 'fields' parameter

- tests/php/indexables/TestPostMultisite.php
Added `cleanUpSites()` command to the multi-site unit tests. The `tearDown()` function was not accessing all the sites used during the test.
None
All of the existing multi-site unit tests now pass.
Need to manually call `cleanUpSites()` when writing new multi-site unit tests.
https://travis-ci.org/10up/ElasticPress/builds/638679051#L641
None
- Added cleanUpSites() to fix multi-site tests
> Added cleanUpSites() to fix multi-site tests

- includes/classes/Indexable/Post/Post.php
Right now we don't do a tax_query for taxonomies called in the root of `WP_Query` e.g.
```php
new WP_Query( [
'tax_name' => 'slug',
] );
```
Should fix #1576.
> Support all taxonomies in root WP_Query

- includes/classes/Command.php
This PR refactors and greatly simplifies how CLI indexing occurs. It removes some confusion recursion. It also adds a CLI flag `--show-errors` which will force the indexing command to output errors for bulk as well as no bulk indexing. I have a feeling this might fix some of the bugs currently being reported.
> CLI Index Refactor

- elasticpress.php
- includes/classes/Elasticsearch.php
- tests/php/indexables/TestPost.php
Moves the `Indexables::factory()->register( new Indexable\Post\Post() );` call into a `plugins_loaded` action.
None.
The indexable post class make a call to Elasticsearch inside its constructor. Since this constructor is being called prior to any other plugins being loaded, any hooks/filters in the other plugins will not run.
Possible breaking changes for existing plugins/themes that interact with EP, but the scope of this is unknown.
Ran all of the existing unit tests locally, all passed.
```
root@350c654785b0:/var/www/html/wp-content/plugins/elasticpress# EP_HOST="http://elasticsearch:9200" ./vendor/bin/phpunit
Installing...
Installing network...
Running as multisite...
WordPress version 5.3.2
Elasticsearch version 7.5.1
Installing WooCommerce version 3.6.5 ...
Not running ajax tests. …
```
> Moved EP indexable posts class registration into a function that runs in the plugins_loaded action

- includes/classes/Indexable/Term/QueryIntegration.php
- includes/classes/Indexable/Term/Term.php
- includes/mappings/term/7-0.php
- includes/mappings/term/initial.php
- tests/php/includes/functions.php
- tests/php/indexables/TestTerm.php
* Updated term mapping for ES 7.0
** Removed `standard` as a filter https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#standard-filter-removed
** Added `index.max_shingle_diff`
** Removed `term` as one of the levels in the mapping array to match the levels of the mapping array for posts.
* Fixed testTermQueryOrderParent()
> Terms indexable updates

- includes/classes/Feature/ProtectedContent/ProtectedContent.php
- includes/classes/Indexable/Post/SyncManager.php
This change does a few things. First, it removes the following post types from indexed by Protected Content:
- revision
- oembed_cache
- custom_css
- user_request
- customize_changeset
- wp_block
While this does break backwards compatibility. Likely, no one is using this post types. They can still be indexed by filtering `ep_indexable_post_types`.
In the sync manager, we removed the `auto-draft` check since that status is not included in the indexable post statuses. We also add a post type check in the delete sync since we don't need to delete posts that aren't indexed based on post type. We also simplify some of the general sync check logic.
Replaces #1499
> Limit Protected Content Post Types

- docs/wp-cli.md
The [cli commands documentation](http://10up.github.io/ElasticPress/tutorial-wp-cli.html) for `get-cluster-indexes` and `get-indexes` is incorrect, it uses underscores in stead of dashes.
> Fix doc for get-cluster-indexes and get-indexes

- CHANGELOG.md
- includes/classes/Command.php
- readme.txt
Adds a simple `clear-index` CLI command to reset the index transient. This is a shortcut for `wp transient delete...`.
> Add clear-index command.

- includes/classes/Command.php
@tlovett1 - It seems the changes in 79d49e944043aa5647ad68f261509d1732d3a897  (#1647) causing a regression when the plugin is not network-wide activated. 
(Alternatively, we can set `define( 'EP_IS_NETWORK', $network_activated );` by removing if statement for making sure the constant defined)
To test, all CLI functions should be tested with and without network-wide as well as network activated and not network activated.
> check constant definition first

- includes/classes/Command.php
fixes overload notice cc/ @tlovett1 
run `wp elasticpress index --setup` and see the output
#1612, #1590
Fix: CLI overload notice during syncing.
> fix overload notice

- includes/classes/Feature/Facets/Facets.php
Skip facet query on product category archives when the WooCommerce feature is not active. These changes prevent breaking the query.
fixes #1662
Fixing product category pages
- deactivate EP Woo feature
- activate EP Facets feature
- visit WooCommerce product category
- see the results
#1662
> Dont make product categories facetable when woo feature is not active

- includes/classes/Indexable/Term/Term.php
In certain situations, term sync is showing a higher index count than the current total e.g. 10/5. This fixes that. I also added hook docs for all the new Term indexable hooks.
> Term sync fix

- includes/classes/Feature/Search/Weighting.php
- tests/php/features/TestWeighting.php
Save weighting settings for each searchable post type,  regardless of `$_POST['weighting']`
The Weighting Engine doesn't store the default weighting settings for a post_type in `elasticpress_weighting`. So it fails when all options are disabled at once. Because it can't save the options when `$_POST['weighting'][$post_type]` is not in place.
1) Register a custom post type. E.g:
```
function epdev_custom_post_type()
{
register_post_type('ep_test',
array(
'labels'      => array(
'name'          => __('Tests'),
'singular_name' => __('Test'),
),
'public'      => true,
'has_archive' => true,
'rewrite'     => array( 'slug' => 'ep-test' ), 
)
);
}
add_action('init', 'epdev_custom_post_type');
```
2) Disable all weighting options for `Test` post_type
3) See the changes are not saving
4) checkout …
> fix: save weighting settings based on post_type

- includes/classes/Indexable/Post/DateQuery.php
- tests/php/indexables/TestPost.php
Expanded DateQuery tests to reach 100% coverage.
Improved unit tests
None
`testStickyPostsExcludedOnNotHome` may be an existing test that is failing.
None
* Expanded DateQuery test coverage
> Expanded DateQuery test coverage

- includes/classes/Feature/WooCommerce/WooCommerce.php
This simply changes the orderby to use `.double` instead of `.long`. Since .long doesn't account for decimals in the Elasticsearch mapping, it can lead to incorrect ordering. By using `.double` it is ensured the orderby is done with a numeric datatype accounting for decimals.
- [x ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ x] My code follows the code style of this project.
> Use double instead on long to account for decimals

- includes/classes/Indexable/Post/Post.php
- tests/php/indexables/TestPost.php
* Increased the code coverage on the \ElasticPress\Indexable\Post class to 100%
* Fixed a bug where both `cat` and `tag` parameters in the root WP_Query args would only pass one of those values to ES.
* Added the `false` bool value to an `ignore_sticky_posts` array check to match the strict type comparison it is doing.
Improved unit tests and bug fixes
None
Verified all existing unit tests passed and added new unit tests to verify the bug fixes.
#1718 
* Fixed a bug where both `cat` and `tag` parameters in the root WP_Query args would only pass one of those values to ES.
* Added the `false` bool value to an `ignore_sticky_posts` array check to match the strict type comparison it is doing.
> Expanded indexable post unit test coverage

- uninstall.php
As per #1760, this PR changes the unset EP_FILE in the uninstall.php file to the value it has in the main file.
During the uninstall process, the magic file [uninstall.php](https://developer.wordpress.org/plugins/plugin-basics/uninstall-methods/#method-2-uninstall-php) is called but the main plugin file is not. With that, the EP_FILE constant is not set and the `( dirname( WP_UNINSTALL_PLUGIN ) !== dirname( EP_FILE ) )` comparison fails. As the uninstall.php is always placed in the plugin's root, it is safe to replace that constant with  `plugin_basename( __FILE__ )`.
We could set the constant in that file too but that is not necessary, as it won't be used anywhere else.
It will be possible to uninstall the plugin via WP Dashboard and WP-CLI.
None.
I've installed the plugin, tried to …
> uninstall.php: Change the EP_FILE const to its value

- includes/classes/Indexable/Post/Post.php
Allow users to turn on sticky posts handling for any request not just when `is_home() === true`, like for REST API calls for example.
This introduces a new filter that allows developers to enable sticky posts on other requests than when `is_home()` is true, eg: for REST API calls ( to provide parity with server-side preloaded states ).
- Allows parity between Server-side loaded content and REST API calls if needed.
- Allows more flexibility for developers to enable/disable sticky posts at their discretion for any query.
- This does not change any logic, just adds the filter.
- This does not change any logic, just adds the filter.
- Adds `ep_enable_sticky_posts` filter to control sticky posts activation per query.
> Allow filtering sticky posts support

- includes/classes/Elasticsearch.php
As related in #1740, non-blocking requests return empty bodies and response codes and that is interpreted as an error by ElasticPress, that retries the query. This PR aims to avoid that behavior, simply avoiding a retry if the response code is 0.
As non-blocking requests will fail async, I don't think we have much choice here.
Stop EP from doing unnecessary requests.
none
1. Set a plugin with 
```
add_filter(
'ep_max_remote_request_tries',
function( $num ) {
return 5;
}
);
```
2. Added this to the `Elasticsearch::remote_request()`
```
error_log( $failures . ' / ' . apply_filters( 'ep_max_remote_request_tries', 1, $path, $args ) . ' / ' . $request_response_code );
```
3. Saved a post as Draft and
4. Read logs.
#1740
> EP Requests: Don't retry if is non-blocking request

- includes/classes/Command.php
Use the feature object instance to test if a feature is active or not. Right now we are using the raw value of the `ep_feature_settings` (site_)option and so bypassing the `ep_feature_active` filter. The code is this PR uses the feature instance and its `is_active` method.
We could use an `apply_filters` call but we wouldn't be able to pass the third argument (the object instance).
Right results for WP-CLI `wp elasticpress list-features` calls.
n/a
I've used
```
add_filter( 'ep_feature_active', '__return_false' );
```
and
```
add_filter(
'ep_feature_active',
function( $is_active, $feature_settings, $feature ) {
if ( 'related_posts' === $feature->slug ) {
$is_active = false;
}
return $is_active;
},
10,
3
);
```
to test.
Closes #1765 
- Fixed the list of active features displayed by the `wp …
> CLI: "wp elasticpress list-features" fix

- includes/classes/Indexable/Post/Post.php
- includes/classes/Indexable/Term/Term.php
- includes/classes/Indexable/User/User.php
- tests/php/indexables/TestPost.php
- tests/php/indexables/TestTerm.php
Change `_source_include` to `_source_includes` to prevent deprecation warning.
1. On the `develop` branch, create and excute a user query with `fields`:
```
$users = new WP_User_Query( array(
'search'        => 'admin',
'search_fields' => array( 'display_name' ),
'fields'        => array( 'ID', 'display_name' ),
'ep_integrate'  => true
) );
```
2. Check the log of elasticsearch, see `Deprecated field [include] used, expected [includes] instead`.
3. Check out this PR, run the query again.
4. Check the log again, don't see new deprecation logs.
Closes #1769
> Fix: field [include] deprecation

- includes/classes/Elasticsearch.php
Hi @tlovett1 ,
This PR is just to simply add a filter to modify the hardcoded timeout for the request for `bulk_index()` and `index_document()`.
The use case for this is for big documents (i.e a 20mb PDF). Without increasing the timeout of the request, they will simply not index.
We have had this problem in the past for a few elasticpress.io clients and currently there's one who is having this issue. Before, we had the `ep_bulk_index_post_request_args` filter but looks like that's no longer available. 
Perhaps the filter should be for the whole request args?
- Index large documents, without it, it is impossible
> Add timeout filters for bulk_index and index_document

- includes/classes/Indexable/Post/Post.php
This PR aims to improve WP_Query root taxonomies detection. Instead of checking if a taxonomy slug is an argument of the query, it checks for the taxonomy `query_var` value, mimicking what WordPress core does [here](https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-query.php#L1114):
```
foreach ( get_taxonomies( array(), 'objects' ) as $taxonomy => $t ) {
if ( 'post_tag' == $taxonomy ) {
continue;   // Handled further down in the $q['tag'] block
}
if ( $t->query_var && ! empty( $q[ $t->query_var ] ) ) {
...
}
}
```
(`$taxonomy` is the slug, `$t->query_var` the query_var).
Although it won't completely solve the problem stated in #1727, it can at least reduce it. Also, we'd be better aligned with the strategy adopted by WP core.
Created the taxonomy as said in #1727 …
> Add root taxonomies to tax_query only when query_var is set

- includes/classes/Feature/Facets/Widget.php
This PR makes the HTML that is passed to the `ep_facet_search_widget` filter valid. This is required because `ob_start()` is started inside the `<div class="terms">` element but closing element is included in the `ob` result
The main benefit here is that it is valid/complete HTML that is being passed.
It is not necessarily a problem is the markup is only being manipulated with str_replace() or similar functions but HTML parsers like `DOMDocument()` will try to auto-correct broken markup and add/remove a `<div>` which will, in the end, cause broken markup
> Facets widget: Move <div> outside ob_start()

- includes/classes/Feature/Facets/Facets.php
- includes/classes/Feature/Facets/Widget.php
Use `wp_register_script` / `wp_register_style` to register (not enqueue script & styles) and only call `wp_enqueue_script` / `wp_enqueue_style` if the assets are really necessary.
Frontend performance improvement when the Facets Widget is only implemented on a few pages.
No kown drawbacks
Added a new Sidebar with a Facet Widget only visible on pages where ìs_search()` is `true` and checked if the scripts and styles are only loaded on these pages.
> Load scripts & styles only when they are really necessary

- composer.lock
This PR just updates the WPAcceptance version. With it, we can get rid of an `undefined variable: script` error while running wpa tests.
Props to @dinhtungdu for the [PR on the WPA repo](https://github.com/10up/wpacceptance/pull/23).
n/a
Tests passing.
n/a
Run tests locally
n/a
n/a
> Update WPAcceptance Version

- includes/classes/Feature/RelatedPosts/RelatedPosts.php
- includes/classes/Feature/SearchOrdering/SearchOrdering.php
Adds a `permission_callback` parameter to all of our `register_rest_route` calls. This was previously not required but in WordPress 5.5, this will now throw a PHP notice if debug is on and this parameter isn't passed. Because we currently aren't doing any sort of permission check, we utilize the `__return_true` function here, which will always return true.
None
Removes PHP notices in WordPress 5.5+ when debug is on
None
With debug on and prior to any changes, tested out the plugin locally. Saw that I was getting 3 PHP notices. After this fix, tested again and didn't get any PHP notices
Fixes #1867
> Add a default permission_callback to all of our custom REST routes

- includes/classes/Indexable/User/User.php
Added new filter `ep_prepare_user_meta_data` to mirror the`ep_prepare_meta_data` in the Post Indexable
> Added Prepare User meta data filter

- includes/classes/Feature/Autosuggest/Autosuggest.php
Makes the default autosuggest selector a proper class.
> Proper autosuggest selector

- wpacceptance.json
Update the script to copy the test-mu-plugins folder content to reflect the same that happens with the normal plugins folder.
I'm setting the EP credentials in a mu-plugin and got this error:
`Before script returned a non-zero exit code: mv tests/wpa/test-mu-plugins ../../mu-plugins`
After making the change proposed in this PR it worked.
n/a
We can easily run tests against external services like EP.io.
n/a
1. Create a mu-plugin inside the `/tests/wpa/test-mu-plugins` folder
2. Set EP_INDEX_PREFIX, ES_SHIELD, and EP_HOST inside of it
3. Run tests
4. See the `Before script returned a non-zero exit code: mv tests/wpa/test-mu-plugins ../../mu-plugins` message
5. Apply the changes
6. The error doesn't happen
> Update before_scripts in wpacceptance.json

- includes/dashboard.php
As advertised - instead of top-level ElasticPress menu being followed by another submenu item reading ElasticPress, that submenu item will read Features.
n/a
Should make it easier to understand what that page is for specifically.
Not seeing any.
Checked in the admin, clicked to different pages and navigated back.
> Rename first EP submenu item to Features

- includes/classes/Feature/Search/Search.php
Hide links to the Weighting Screen and the Synonyms Screen inside the Post Search box when in Multisite.
n/a
Remove links to pages the user should not access.
n/a
1. Created a MU site
2. Network activated EP
3. Clicked on links: both screens broken
4. Network deactivated EP
5. Activate EP per site
6. Clieck on links: screens look good
#1811
> Hide links to the Weighting and Synonyms Screens when in Multisite

- includes/classes/Indexable/Post/SyncManager.php
As described in #1857, EP will trigger a sync every time any metadata is changed (including `_edit_lock` and any other). This PR aims to only sync when metadata that will really be stored in ES is changed.
To narrow down the allowed meta I'm using the `ElasticPress\Indexable\Post\Post::prepare_meta()` method, as it'll run all filters a dev would use: ep_prepare_meta_data, ep_prepared_post_meta, ep_prepare_meta_allowed_protected_keys, ep_prepare_meta_excluded_public_keys. ep_prepare_meta_whitelist_key, and ep_prepared_post_meta.
We could avoid a ES sync just for `_edit_lock`.
Less requests made to the ES server.
n/a
I've looked at docker logs and made some `error_log()` calls. I've changed a default meta data (`my_test`) and also WooCommerce SKUs. Both were updated successfully.
#1857
- …
> Post metadata: Just queue post if the meta changed is allowed

- includes/classes/Indexable/Post/SyncManager.php
#1827 issues that deleting a post from the admin view, does not delete the post from ES, but rather, changes the post_status to `trash`.
By resetting the `sync_queue`, no more actions will be handled, after the `wp_redirect` kicks in.
Cannot run phpunit, as I'm running in Docker, and don't have svn and such locally installed.
According to the screenshots from #1827, deleting a post from admin view, does not delete the post/document in ES (but changes the post_status of that document to `trash`.
After apply my patch, the deleted document is not found in ES anymore.
Code could have unintended impact on other parts of the plugin.
Added: reset `sync_queue` after deleting post.
> (fix): reset queue after delete post

- includes/classes/Indexable/Post/SyncManager.php
- includes/classes/Indexable/Term/SyncManager.php
- includes/classes/SyncManager.php
This fixes a bug where when network activated non-indexable sites would still sync posts.
> Check if site is indexable before syncing

- wpacceptance.json
This PR changes one of the before_scripts commands, creating the mu-plugins before moving anything into it.
n/a
Possibility of adding mu-plugins without error. This is especially useful to run WP Acceptance tests against other servers.
n/a
Changed and run it a couple of times with --show_browser (to check which server was being used).
n/a
> [WP Acceptance] Create a mu-plugins folder first

- includes/classes/SyncManager.php
In the `can_index_site` function, we use the wrong condition to check if the current site is network activated. This PR fix that condition.
Fixes #1917
> Fix: PHP Warning due to missing quotes

- includes/classes/Feature/Facets/Widget.php
This PR introduces a new `ep_facet_search_get_terms_args` filter to the `get_terms()` call we have inside the Facets widget.
With this, developers will be able to easily tweak that function call. It can be useful, for example, to exclude some unwanted terms like "Uncategorized". The code would be something like:
```
add_filter(
'ep_facet_search_get_terms_args',
function( $args ) {
$args['exclude_tree'] = [ 1 ];
return $args;
}
);
```
Open to suggestions.
Explained above.
n/a
I've added the filter and tested the snippet above.
n/a
Added the "ep_facet_search_get_terms_args" filter, making it possible to change the get_terms() call inside the Facets widget.
> Facets: Create a new "ep_facet_search_get_terms_args" filter

- includes/dashboard.php
See https://github.com/10up/ElasticPress/issues/1914
This fix disabled sync AJAX callback if EP_DASHBOARD_SYNC is set to false.
Currently the constats only remove the sync buttons.
Properly disable the dashboard sync feature.
Possible confusion from user trying to sync via dashboard.
> Disable dashboard sync AJAX callback if EP_DASHBOARD_SYNC is set to false.

- includes/classes/Feature/Autosuggest/Autosuggest.php
For autosuggest, the current code just adds the `post_title.suggest` field to multi_match clauses that contain `fuzziness`. As the new algorithm uses `slop`, the ngram field isn't added to the query.
We probably could test just for `! empty( $current_bool_should['multi_match']['fuzziness'] )` perhaps?
Partial matches for autosuggest working again.
n/a
> Add the `post_title.suggest` field when using the new algorithm

- elasticpress.php
- includes/classes/Feature/Search/Search.php
When the plugin is creating the `highlight.fields` section in the Elasticsearch query, it should iterate over an array with just strings. This PR removes any array WP_Query's `search_fields` can contain and re-add any meta key it may have.
Fixes #1931
> Keep only strings in the $fields_to_highlight array

- includes/classes/Command.php
- tests/wpa/WpCliTest.php
- uninstall.php
This PR adds the following two commands as well as necessary data structures and acceptance tests to determine index status on an index started via an automated session.
`wp elasticpress get-index-status`
Returns the following:
```{"indexing":false,"method":"none","items_indexed":0,"total_items":-1}```
`wp elasticpress get-last-cli-index [--clear]` The optional clear flag will clear the saved status from the database
Returns an empty json array or the following:
```{"total":2006,"synced":2006,"end_time_gmt":1602177690,"total_time":24.418,"errors":[]}```
After an analysis of existing commands and endpoints there wasn't another method we could find existing that would serve the purpose. We are open to further suggestions.
This would allow an automated system handling the plugin at scale to …
> Feature: Track CLI index in a headless fashion

- includes/classes/Indexable.php
Workaround for `strtotime` potentially producing valid timestamps that would result in 5 digit years resulting in an `Uncaught Error: Call to a member function getTimestamp() on bool` in `date_i18n`.
Props @rinatkhaziev
cc: @nickdaugherty @pschoffer @netsuso @parkcityj
N/A
Prevents errors from halting execution due to the way dates are handled in PHP.
N/A
A site wouldn't index on a specific post. After applying this PR, it was indexed smoothly.
Fixed timestamp check to avoid creating dates with 5 digit years which currently results in errors. Props @rinatkhaziev
> Don't use timestamps that cause 5 digit years

- includes/classes/Elasticsearch.php
Added an action that fires after an invalid response from Elasticsearch.
Props @hanifn
N/A
Allows invalid responses from Elasticsearch to be handled.
N/A
We needed a way to detect invalid Elasticsearch responses. After applying this PR, we could apply logging and other measures to keep a handle on things.
Added ep_invalid_response action. Props @hanifn
> Added action that fires after an invalid response from Elasticsearch

- includes/classes/Feature/Search/Search.php
Added filters to allow setting the decay function and score mode for data weighting.
N/A
Allows setting of the decay function and score mode via filters in addition to the others that were already there.
N/A
We needed to change the decay function and score mode for specific queries. After applying this PR it was trivial to do.
Added filters for setting the decay function and score mode for date weighting.
> Added decay function and score mode filters for weighting

- includes/classes/Command.php
Switched from WPCLI errors to WPCLI warnings in commands. This is because `WP_CLI::error` stops execution which means that the retry functionality during indexing doesn't work as expected.
Props @rinatkhaziev
cc: @nickdaugherty @pschoffer @netsuso @parkcityj
N/A
Retry functionality starts working as expected.
Execution no longer stops when an error in encountered during indexing via WPCLI.
We were having indexing operations not retrying when they should have. After applying this PR, the retry functionality worked as expected.
Changed errors to warnings in index command to allow retry functionality to work as intended. Props @rinatkhaziev
> Switched from errors to warnings in index command

- includes/classes/Feature/Documents/Documents.php
Added a filterable `$filesystem_args` argument to allow for non-standard WordPress filesystem setups.
No alternate designs considered.
Allows the WP filesystem to open documents and index their contents properly on installations where the WP_Filesystem() defaults are insufficient (eg, SSH2-based access).
Without the filesystem args:
- Reindex documents
- Search for a string unique to a PDF uploaded to the site
- Search fails
With the filesystem args:
- Reindex the documents
- Search for a string unique to a PDF uploaded to the site
- Search finds the PDF
I don't believe this will adversely affect other uses of `WP_Filesystem()` in the code.
* Added `$filesystem_args` to the Document feature
* Added `ep_filesystem_args` filter
> Adds filterable arguments to WP_Filesystem() call (addresses #1972)

- includes/classes/Feature/Search/Synonyms.php
When an error occurred in the Synonyms admin page, just the following message is showed: `There was an error updating the synonym list`. This happens because the message is overwritten in [line 212](https://github.com/10up/ElasticPress/blob/96d518f5cf0a803f27b4ccd4177238d73b09639e/includes/classes/Feature/Search/Synonyms.php#L212) (ElasticPress/includes/classes/Feature/Search/Synonyms.php).
This change removes the content of line 212 and adds a default message in the [switch/case](https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/Search/Synonyms.php#L200). 
Show a more specific message to error.
n/a
This has been tested manually on the Synonyms page with no indexed data.
#1941 
Fixed admin notice on the Synonyms page
> Fix admin notice on the Synonyms page

- elasticpress.php
- includes/classes/Feature/WooCommerce/WooCommerce.php
- includes/classes/Upgrades.php
As per #1722 , when we add the WooCommerce fields to the query via search_fields parameter, the weighting engine is completely ignored.
This PR aims to add WooCommerce fields to the _Manage Search Fields & Weighting_ Screen, giving the user the ability to enable or not WooCommerce fields and change their weights. This is a cleaner and more elegant approach than the one suggested on #1785 .
This is how the _Product_ post type box looks like with the initial version of the PR:
Note the "SKU" field and the absence of the "Author", which is removed by the current code.
Keep weighting functionality AND having WC fields.
I've checked the ES query in Debug Bar
#1722 
Add WooCommerce fields to the _Manage Search Fields & Weighting_ Screen.
> [WooCommerce] Add Fields to the Weighting Dashboard

- includes/classes/Indexable/Post/Post.php
This PR adds support for `author__in` and `author__not_in` parameters for closer WP_Query compatibility.
Fixes #1974
> Add: author__in and author__not_in support

- includes/classes/Feature/Search/Synonyms.php
- includes/classes/Feature/Search/Weighting.php
- includes/classes/Feature/SearchOrdering/SearchOrdering.php
- includes/classes/Screen.php
- includes/dashboard.php
Some pages are showing an incorrect or inconsistent title page. This change updates the title pages to follow the pattern "ElasticPress PAGE_NAME".
Keeping consistency through the plugin.
n/a
#2009
Fixed inconsistent title pages.
> Fix incorrect titles page

- .travis.yml
- includes/classes/Feature/Search/Search.php
- includes/classes/Indexable.php
- tests/php/features/TestSearch.php
- tests/php/features/TestSynonyms.php
- tests/php/includes/classes/BaseTestCase.php
- tests/php/indexables/TestPost.php
- tests/php/indexables/TestPostMultisite.php
Fixes some code to pass existing unit tests, updated some broken unit tests, and applies the 3.4 algorithm filter to other unit tests to allow them to start passing. Note: This contains some changes that were done as part of the [Composer V1 pull request](https://github.com/10up/ElasticPress/pull/2022)
Allows unit tests to start passing again
This does not contain new unit tests to cover ElasticPress 3.5 updates.
Updated unit tests are now passing: https://travis-ci.com/github/petenelson/ElasticPress/jobs/470265557
* Fixes some code to pass existing unit tests, updated some broken unit tests, and applies the 3.4 algorithm filter to other unit tests to allow them to start passing.
> Unit Test Updates

- .travis.yml
Unit tests are currently unable to run due to [Composer v2](https://travis-ci.org/github/10up/ElasticPress/jobs/753550203#L270) being used in the CI process. This is causing `composer install` to fail. Adding `composer self-update --1` forces Composer to use v1 and allows the `composer install` to work and unit tests to run.
Eventually this change can be reverted once all the affected packages are updated to support Composer v2.
Verified via CI: https://travis-ci.com/github/petenelson/ElasticPress/jobs/469862924
Some of the unit tests themselves are failing, but this update now allows the unit tests to run.
* Force Composer v1 for Travis CI unit tests
> Force composer to v1

- includes/classes/Elasticsearch.php
This PR changes the way the plugin decides if the `EP-Search-Term` header should be sent or not. As it was designed to be used by ElasticPress.io, it now includes a test using `Utils\is_epio()`. The value of the header is now escaped too.
Also, it introduces the new `ep_query_send_ep_search_term_header` filter. Returning `false` to it will avoid the header from being sent.
For non-EP.io customers relying on that header, here is a snippet that can be used to bring it back:
```
add_filter(
'ep_query_send_ep_search_term_header',
function ( $old_value, $query_args ) {
return ! empty( $query_args['s'] ) &&
! is_admin() &&
! isset( $_GET['post_type'] );
},
10,
2
);
```
n/a
Remove an unnecessary header for non-EP.io clients.
People relying on that header will need to add that snippet.
Installed …
> Add the ep_query_send_ep_search_term_header filter

- includes/classes/Feature/Search/Synonyms.php
- includes/classes/Upgrades.php
The synonyms list is saved in a custom post type that is not accessible through the admin dashboard. However, when the synonyms list is updated, the post type is changed from `ep-synonym` to `post`. 
As a consequence, this post becomes available in the list of posts where can accidentally be deleted. If the post with the synonyms list is deleted, it's no possible to save a new one because the plugin references the deleted post and raises an error.
This change ensures that the custom post type doesn't change on the update and adds an upgrade routine to fix this problem.
Users can add/update the synonyms list.
Fixes: #1941 
Fixed on update the synonyms list.
> Fix synonyms list update

- includes/partials/settings-page.php
Add missing input type in the Subscription Username's field.
Before change:
After change:
Input on the Settings page has the same style.
Fixes: #2035 
Fixed input style on the Settings page.
> Fix input with different style

- includes/classes/Feature/Search/Synonyms.php
- includes/classes/Upgrades.php
- tests/php/features/TestSynonyms.php
This change refactors the `get_synonym_post_id` function to remove the dependence of `elasticpress_synonyms_post_id` option.
> Remove elasticpress_synonyms_post_id option

- includes/classes/Feature/Facets/Facets.php
Introduces a new filter (`ep_is_facetable`) to allow bypassing the checks in `Facets\is_facetable()`, effectively allowing any query to have facets handled natively.
Currently the `is_facetable()` checks only allow for queries that have `$query->is_main_query()` set to true. This excludes any and all REST API requests, either through the native `wp/v2/search` endpoint or via custom endpoints, because the REST API does not set a main query in core and forcing a query to be the main query is likely to cause other issues.
This change allows developers to determine that specific queries should have aggregations even if they are not the main query.
This change should be invisible to current installs and won't have any effects unless the filter is used.
Tested with both the native Search …
> introduce a filter to allow custom queries to be facetable

- includes/classes/Indexable/Post/Post.php
This is a fix for bug https://github.com/10up/ElasticPress/issues/2065. The 'from' statement in the query is an empty string when it needs to be an int. Line 1361 needs to have the value cast as an int to convert the empty string to a 0.
Some themes appear to not be handling the 'offset' correctly and are passing an empty string (which fools the isset check). The empty string is making its way to ES, which causes a break as it's invalid. Casting the empty string to an int converts it to a 0 which is valid in ES.
N/A
Tested this on a live site using this theme: https://themeforest.net/item/newspaper/5489609
- number_format_exception fix for 'from' statement caused by some themes.
> Fix for https://github.com/10up/ElasticPress/issues/2065

- includes/classes/Indexable/Post/Post.php
As the docblock for the `ep_formatted_args` filter is wrongly mentioning `ep_formatted_args_query`, we currently don't have a http://10up.github.io/ElasticPress/ep_formatted_args.html generated.
> Fix docs for the ep_formatted_args filter

- includes/classes/Command.php
- includes/classes/Indexable/Post/Post.php
This PR adds two new WP-CLI commands:
- `wp elasticpress set-algorithm-version [--version=<version>] [--default]`
- `wp elasticpress get-algorithm-version`
It also adds a PHP docblock for the `ep_search_algorithm_version` filter.
Users will be able to change the search algorithm version without PHP code.
Add the new `set-algorithm-version` and `get-algorithm-version` WP-CLI commands.
> WP-CLI commands to get and set the search algorithm version

- includes/classes/Feature/Search/Weighting.php
- includes/classes/Indexable/Post/Post.php
As outlined in #2101, due to the way ElasticPress builds the query sent to Elasticsearch, quite often it's hard to manipulate it. This PR adds a new `ep_query_weighting_fields` filter and add two more parameters to `ep_formatted_args_query`.
```
function set_precise_search( $query, $args, $search_text, $search_fields ) {
if (
! @isset( $query['bool']['should'][0]['multi_match']['fields'] ) ||
! @isset( $query['bool']['should'][0]['multi_match']['query'] )
) {
// not the query we're looking for
return $query;
}
$query = array(
'bool' => array(
'should' => array(
array(
'multi_match' => array(
'query'  => $search_text,
'type'   => 'phrase',
'fields' => $search_fields,
'boost'  => 5,
'slop'   => 5,
),
),
array(
'multi_match' => array(
'query'  => $search_text,
'type'   => 'phrase',
'fields' …
```
> Add filters for easier search algorithm manipulation

- docs/meta.json
- docs/theme-integration.md
Adds documentation for how the autosuggest is attached to forms, and a guide on how to use #2070 to display a loading indicator while suggestions are fetched.
Previewed on GitHub.
#2100 
#2070 
#1610
> [Docs] Add theme integration docs

- includes/classes/Command.php
- includes/classes/Feature/Autosuggest/Autosuggest.php
- includes/classes/Features.php
- includes/dashboard.php
This PR fixes the problem outlined in #2104. It also adds some new actions:
- ep_wp_cli_after_index
- ep_after_dashboard_index
- ep_cli_before_set_search_algorithm_version
- ep_cli_after_set_search_algorithm_version
- ep_after_update_feature
- ep_cli_before_clear_index
- ep_cli_after_clear_index
Closes #2104 
- Add new actions: ep_wp_cli_after_index, ep_after_dashboard_index, ep_cli_before_set_search_algorithm_version, ep_cli_after_set_search_algorithm_version, ep_after_update_feature, ep_cli_before_clear_index, and ep_cli_after_clear_index
> Autosuggest: Helper function to delete cached query

- assets/js/autosuggest.js
- assets/js/synonyms/components/editors/AlternativesEditor.js
- assets/js/synonyms/components/editors/SetsEditor.js
- assets/js/synonyms/components/shared/LinkedMultiInput.js
- assets/js/synonyms/utils.js
Adds missing inline JS documentation to resolve linting warnings.
n/a
Better docs, no more linting warnings.
n/a
Run `npm run lint-js`.
#2111 
Added missing inline JS documentation.
> Add missing JS documentation.

- includes/classes/Feature/ProtectedContent/ProtectedContent.php
As stated in ##2123, the Protected Content feature should never be auto-activated even when using ElasticPress.io.
1. Deleted site options
2. Made the change in the code
3. Setup the plugin using EP.io
4. The feature was not activated.
Fixes #2123
- The Protected Content feature isn't auto-activated when using ElasticPress.io anymore
> Don't activate Protected Content by default when using EP.io

- includes/classes/Feature/Search/Search.php
This PR adds a new `ep_highlight_should_add_clause` filter to let developers decide where the `highlight` clause should be added to the ES query.
n/a
Developers can use highlight in AJAX and REST requests, for example.
n/a
1. Added the code
2. Tested if everything worked as before
3. Added `add_filter( 'ep_highlight_should_add_clause', '__return_true' );` to a mu-plugin
4. Visited https://ep-352.test/wp-json/wp/v2/posts?search=lorem and saw <mark> tags
Fixes #2051
Add a new filter to let developers decide where the `highlight` clause should be added to the ES query
> Add the `ep_highlight_should_add_clause` filter

- uninstall.php
Some options and transients are not removed after uninstalling the plugin. This change adds these missing options and transients to be removed on uninstall process.
All options and transients are removed.
Fixes: #1953
Fixed uninstall process to remove all options and transients.
> Add missing options and transients to be removed on uninstall

- includes/classes/Feature/Facets/Facets.php
Although I could not reproduce the problem stated in #1938, this PR adds a check before iterating over the aggregation buckets.
fixes #1938
Add an extra check in the iteration over the aggregations.
> Facets: Check if $agg['buckets'] really exists

- includes/classes/Feature/Search/Search.php
This change updates the default `boost_mode` from `sum` to `multiply`. Using `sum` achieves a smaller effect on decaying old content. So old content can still surface at the top of the search results.
Old content turns less relevant in search.
1. Creating posts with a date range between 2009 and 2021.
2. Searched for a term that is common in posts from 2009 and 2021
3. The posts from 2021 are at the top of the search.
Closes: #2042 
Change the default boost_mode to multiply.
> Update the default boost_mode from sum to multiply

- .github/workflows/test.yml
This is an attempt to fix the ` Warning:  mysqli_real_connect(): The server requested authentication method unknown to the client [caching_sha2_password] in /tmp/wordpress/wp-includes/wp-db.php on line 1653` error, like https://github.com/10up/ElasticPress/runs/2122309836
> Bump PHP version for PHPUnit tests

- includes/classes/Command.php
Add terms indexes to the status and stats WP-CLI commands.
> WP-CLI: Add terms to status and stats

- tests/php/features/TestSearch.php
This function should return $args, as it is used by a filter.
> Fix catch_ep_formatted_args()

- assets/js/autosuggest.js
Applies a `epAutosuggestItemHTMLFilter()` function to autosuggest items to allow filtering the HTML of autosuggest results.
In this implementation the filter callback only receives the option object as the second argument, and the option index as the third argument. These can be used to reconstruct the original HTML, or a variation of it, if desired. This means that a custom filter would need to implement any required escaping, as well as highlighting.
An alternative approach could be to also pass the pre-processed escaped text and highlighted results text as arguments to the callback. 
The appropriate approach would depend on how much hand holding we want to do.
Developers can provide their own HTML for autosuggest result items.
The potential for autosuggest results to break if future …
> Allow filtering the HTML of Autosuggest items.

- docs/wp-cli.md
As stated in #2115, any of the `*-feature` WP-CLI commands accept the `--network-wide`. This PR updates the documentation reflecting that.
- Updated WP-CLI commands documentation
> Update WP-CLI *-feature commands docs

- includes/classes/Feature/Autosuggest/Autosuggest.php
As stated in #2126, enqueueing Autosuggest scripts on the frontend while EP is indexing makes the autosuggest query to be empty, generating a `TypeError: t.replace is not a function` error. This PR adds a check, completely avoiding autosuggest to enqueue anything while EP is indexing.
Manual. Indexing with --nobulk and checking.
Fixes #2126 
- Autosuggest JavaScript is not loaded anymore when ElasticPress is indexing the content.
> Autosuggest: don't enqueue scripts if EP is indexing

- includes/classes/Elasticsearch.php
Avoids `Undefined variable: closed` by defining the variable preemptively.
`n/a` - it is a kinda simple solution so not sure of different approaches.
No notice
`n/a`
Ran on our dev-environment... the notice is gone
- [x I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [`n/a`] My change requires a change to the documentation.
- [`n/a`] I have updated the documentation accordingly.
- [`n/a`] I have added tests to cover my change.
Fixes https://github.com/10up/ElasticPress/issues/2155
Fixed `Undefined variable: closed` notice in `update_index_settings`.
> Avoids undefined variable notice

- includes/classes/Indexable/Post/QueryIntegration.php
This change removes the references to `posts_by_query` property. This property was used by two functions that were removed by the commit [6d71e6c39f5bab11df49580ddcb813fef02ff9fc](https://github.com/10up/ElasticPress/commit/6d71e6c39f5bab11df49580ddcb813fef02ff9fc) 
Closes: #1762
> Remove references to posts_by_query property

- includes/classes/Indexable.php
- tests/php/indexables/TestPost.php
This change adds support to NOT LIKE operator for meta_query. 
Adds a new way to filter posts.
This has been tested manually adding a custom field using [ACF](https://wordpress.org/plugins/advanced-custom-fields/) and querying with the operator NOT LIKE.
1. Adds a check box field with the options red, green, and blue;
2. Set this field in some posts;
3. Query using NOT LIKE 
```php
$args = array(
'ep_integrate' => true,
'meta_query'   => array(
array(
'key'     => 'checks',
'value'   => 'red',
'compare' => 'NOT LIKE',
),
),
);
$the_query = new WP_Query( $args );
```
Closes: #2015 
Added support to NOT LIKE operator for meta_query
> Add support to 'NOT LIKE' operator for meta_query

- includes/dashboard.php
This change adds a new filter to show or not the ElasticPress Indexing option in the Sites screen (`wp-admin/network/sites.php`).
This has been tested manually. Adding the code below is expected that the ElasitcPress Indexing option doesn't appear in the Sites screen.
```php
add_filter( 'ep_show_indexing_option_on_multisite', '__return_false' );
```
Closes: #1893 
Added the filter ep_show_indexing_option_on_multisite.
> Add new filter to show or not ElasticPress Indexing option

- includes/classes/Indexable.php
The index_name is transformed in lowercase before the index creation in Elasticsearch.
Change suggested by @felipeelia https://github.com/10up/ElasticPress/issues/2166#issuecomment-820674767
Uppercase text in Elasticsearch aren’t allowed so this fix transforms the index name in lowercase before creating an index
1. Installed WordPress an uppercase folder so the baseurl was: https://elasticpress.test/UPPERCASE_FOLDER ;
2. installed ElasticPress plugin and activated;
3. configured ElasticPress to a self hosted Elasticsearch server;
4. syncronized -> failed to create index;
5. applied the fix;
6. syncronized -> index created;
7. created some contents: they are searchable and the index health page is OK
Closes: #2166 
Fixed issue with uppercase in siteurl
> Set index in lowercase

- .github/workflows/no-response.yml
This PR adds a new GitHub Action that checks issues with the `reporter feedback` label and if there's no response in 3 days will auto-close the issue.
Keep as-is with no automation or adjust the schedule this runs, the days to wait until closing, and/or the closing comment.
No longer have to check the `reporter feedback` label weekly to see which items can be closed.
No identified.
This is current running on https://github.com/desktop/desktop/blob/development/.github/no-response.yml && https://github.com/github/docs/blob/6d7b73256f86778cd0e0045d54a6e9acea128ce6/.github/workflows/no-response.yaml and is well-documented at https://github.com/lee-dohm/no-response so I'm fairly comfortable this will work.
n/a
```
- Project automation via GitHub Action (props to the magnificent @jeffpaul).
```
> Add GitHub Action to auto-close non-responsive `reporter feedback` issues after 3 days

- includes/classes/Indexable/Post/Post.php
- tests/php/indexables/TestPost.php
This change updates the plugin to handle `post_mime_type` argument when it has an array with a MIME type without the subtype i.e `image` instead of `image/png`.
It's possible to search images when using the Gutenberg editor or Web Stories plugin.
1. Enable document indexing
2. Enable admin and AJAX via `ep_admin_wp_query_integration` and `ep_ajax_wp_query_integration`
3. Edit a post with the block editor
4. Add a new image block to bring up the media modal
5. Use the search bar to search for an image
6. See the image
Closes: #1604 #2206
Fixed post_mime_type argument issue when it has an array with a MIME type without the subtype
> Fix post_mime_type argument

- includes/classes/Feature/SearchOrdering/SearchOrdering.php
none
`current_user_can` should only be passed simple strings/integer not complete objects.
---
---
---
Found the Solution here:
https://wordpress.org/support/topic/object-of-class-wp_post-could-not-be-converted-to-string/
Tested in newest ElasticPress und WordPress Version.
none
Fixed: Creating Custom Results with Feature "Sortable" enabled, could throw an error
> bugfix: current_user_can check in Feature/SearchOrdering

- includes/partials/header.php
Issue #2286 
This was the least intrusive option. The second option would be tooltips on each icon which would require additional javascript. The third option would be to add a text label just below the icon which probably involves some sort of design change and sign-off.
1. Screen readers will be able to identify the links
2. New users will understand the icon's function before selecting it
To verify, I went to the wp-admin dashboard for the plugin and hovered over each icon to see the title attribute.
Also ran `composer run lint-fix` in my editor to make sure my code formatting was correct.
- [X ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ X] My code follows the code style of this project.
Add title attributes and aria-labels to each icon hyperlink in the header …
> Add aria-labels and title attributes to icon hyperlinks in the header toolbar

- run-wpacceptance.sh
This PR changes the regex used to get Page Crashed errors from WP Acceptance tests.
Closes #2311
Fixed: WP Acceptance tests and Page Crashed errors
> Fix: WP Acceptance tests and Page Crashed errors tolerance

- includes/classes/Indexable/Post/Post.php
- tests/php/indexables/TestPost.php
Fixes #2242 
As WordPress core sets the category_name parameter when performing a Tax Query if you are doing an id's search, this conflicts with this check EP does here: https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/Post.php#L1003
This problem only applies to the category taxonomy.
> Fix category slug used when doing cat Tax Query with ID

- .github/hookdoc-tmpl/README.md
- CHANGELOG.md
- README.md
- docs/install.md
- elasticpress.php
This PR updates all references to the minimum PHP version required by the plugin.
Closes #2292
Changed: Minimum supported version of PHP bumped to 5.6.
> Update PHP Version info (5.4 -> 5.6)

- includes/classes/Indexable.php
This is inspired by https://github.com/Automattic/ElasticPress/pull/113
It seems that `new \DateTime( $meta_value, \wp_timezone() );` throws not only exception but also a `E_WARNING` in certain cases.
There is the `date_create` alternative, that according to [manual](https://www.php.net/manual/en/function.date-create.php) is an alias. While testing it though, I found that, it returns false on failure and does **NOT** throw an exception or warning (as far as I can see).
There are already unittests covering this function that are passing and also testing on the local dev-environment results in good results.
Changed - Meta parsing tweak to avoid `E_WARNING`s
> Use date_Create that does not throw exception or warning

- tests/wpa/BasicTest.php
- tests/wpa/DashboardSyncTest.php
- tests/wpa/GeneralTest.php
- tests/wpa/HighlightingTest.php
- tests/wpa/WpCliTest.php
- tests/wpa/features/AutosuggestTest.php
- tests/wpa/features/DocumentTest.php
- tests/wpa/features/ProtectedContentTest.php
- tests/wpa/features/RelatedPostsTest.php
- tests/wpa/features/SearchTest.php
- tests/wpa/features/WooCommerceTest.php
- tests/wpa/inc/TestBase.php
- tests/wpa/indexables/UserTest.php
In the Widgets Edit Screen, it seems sometimes WP keeps a dirty state even after a successful save. When that happens, we get stuck with a "Are you sure you want to leave...?" message, and tests fail due to a timeout. Clicking on the "Update" button again seems to fix the issue.
In #2336 a typo was fixed but the WPA test is still checking for the wrong string.
This PR adds a new `moveTo()` method to the `TestBase` class. Using this method, instead of relying on the usual `Actor::moveTo()` will make the test suite retry to access the page until it succeeds or fails with any error other than `Page crashed`.
Closes #2351
> WP Acceptance Fixes

- includes/classes/Indexable/Term/Term.php
- tests/php/indexables/TestTerm.php
Currently, we are using `if ( ! empty( $query_vars['parent'] ) ) {` which isn't true when `parent = 0`. This PR changes the test to use `isset()` instead.
Closes #2232
> Terms: Use $query_vars['parent'] even when equals 0

- includes/classes/Indexable/Post/Post.php
This PR splits `Post::determine_mapping_version()` in two different methods, so we can:
1. Early return if a version is already determined
2. Keep the `ep_post_mapping_version_determined` filter being executed at the end of the process.
It also fixes the check for ES 7.
Closes #2332 
Closes #2331
- Fixed: Mapping version determination does not send false positives for ES 7 anymore.
> Changes in mapping version determination

- includes/classes/Feature/Autosuggest/Autosuggest.php
This PR addresses the problem outlined in #2346 and improves the readability of the `Autosuggest::adjust_fuzzy_fields()` method.
- Some early returns and more comments will (hopefully) make the method easier to understand
- `term_suggest` is now used for autosuggest searches
Closes #2346 
Fixed: In addition to post titles, now autosuggest also partially matches taxonomy terms.
> Autosuggest: Major rewrite of `adjust_fuzzy_fields`

- includes/classes/Indexable/Term/QueryIntegration.php
- includes/classes/Indexable/Term/SyncManager.php
- tests/php/indexables/TestTerm.php
As stated in #2365, when a term is deleted, it is not removed from the ES index, as `current_user_can( 'delete_term', $term_id )` will fail after the term deletion. This PR changes the hook used for `action_sync_on_delete`.
Closes #2365
Fixed: Deleted terms are now properly removed from the Elasticsearch index.
> Fix Term deletion

- docs/wp-cli.md
- includes/classes/Command.php
This PR updates our WP-CLI commands documentation. It was generated with this [WP-CLI command](https://github.com/felipeelia/cli-command-docs) using:
```
wp cli-command-docs elasticpress --custom-order=index,activate-feature,deactivate-feature,list-features,get-algorithm-version,set-algorithm-version --remove=delete_transient_on_int,custom_get_transient --custom-intro='The following WP-CLI commands are supported by ElasticPress:' > docs/wp-cli.md
```
Another PR will follow this one to make this process automatic.
WP-CLI already relies on the DocBlock above each subcommand. Generating the documentation from it we will have both things always sync'd.
None. If someone wants to contribute with WP-CLI documentation specifically, it should be only a matter of updating the docblock in …
> Update WP-CLI documentation

- includes/classes/Command.php
During some testing, it was discovered that `wp elasticpress stop-indexing` doesn't reliably terminate the execution of an already-running process.
I think this is due to the cache value being stuck in local memory, this should help to prevent that by always forcing the remote fetch from the object cache backend.
Props @rinatkhaziev for https://github.com/Automattic/ElasticPress/pull/108
N/A
The command will be more reliable in terminating the execution of an already-running process.
None I can think of.
1. Check out PR.
2. Spin up an indexing process in a memcached-enabled environment
3. Run `wp elasticpress stop-indexing` from another session
4. Repeat the process and verify it gets interrupted properly.
Fixed: Force fetching ep_wpcli_sync_interrupted transient from remote to allow for …
> Force fetching ep_wpcli_sync_interrupted transient from remote to allow for more reliable remote interruption

- includes/classes/Indexable/User/User.php
We noticed that there was a typo for the users query resulting in a duplicate `orderby` clause:
https://github.com/10up/ElasticPress/blob/b14ab9deee5e1c8b5609c9c210be0b91a3b8a97a/includes/classes/Indexable/User/User.php#L735
This resulted in the below query:
```
SELECT SQL_CALC_FOUND_ROWS ID FROM wp_users ORDER BY ‘ID’ ‘ID’ LIMIT 0, 350
```
`sanitize_sql_orderby()` is for sanitizing the ORDER BY clause for variable use in the $wpdb statement. Variable usage is for avoiding quotes since `$wpdb->prepare()` uses quotes in placeholders and that doesn't play nicely with mariadb. 
Props @brettshumaker https://github.com/Automattic/ElasticPress/pull/97, @pschoffer https://github.com/Automattic/ElasticPress/pull/112/files
N/A.
No more duplicate orderby clause!
None that I can tell.
Fixed: …
> Remove duplicate orderby for users query

- includes/classes/Indexable/Comment/Comment.php
Offset is not accounted for when assigning the default size below for comment queries:
https://github.com/10up/ElasticPress/blob/4a2547e40891895e93361d6063d7f9ddd6e3aa71/includes/classes/Indexable/Comment/Comment.php#L75-L81
In not doing so, we could potentially hit the `ep_max_results_window` if an offset is passed in. Therefore, if we are using the default value for `ep_max_results_window`, we should account for the sum of offset and size being equal (or less than) the maximum results window.
From https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html:
> index.max_result_window The maximum value of from + size for searches to this index. Defaults to 10000. Search requests take heap memory and time proportional to from + size and this limits that memory. 
N/A. …
> When using default max result window value for size, we should account for offsets

- includes/classes/Elasticsearch.php
It would be nice if we could pass in the `$type` parameter into the `ep_do_intercept_request` filter:
https://github.com/10up/ElasticPress/blob/5bb9d76ff4bfd85761e4416a892d731e62cdf33d/includes/classes/Elasticsearch.php#L1067-L1071
This way, we have the flexibility of intercepting the request based on the type of request.
N/A.
We would be able to intercept the request based on the type of request.
Those hooking onto the filter already may need to update their filter arguments
Changed: Add $type parameter to ep_do_intercept_request filter
> Add $type parameter to ep_do_intercept_request filter

- includes/classes/Indexable/Post/Post.php
This PR caches the detected Posts mapping version for a day. This way, we don't send get_mapping calls on every request but we are still able to detect if the ES server was upgraded in a timely manner. People wanting to change that period can do that via the new `ep_post_mapping_version_cache_expiration` filter.
Closes #2432
Changed: Cache the detect posts mapping version, avoiding get_mapping calls in all admin requests.
> Cache the post mapping version

- includes/classes/Feature/Search/Weighting.php
- tests/php/features/TestWeighting.php
This PR adds a new filter, so developers can enable some taxonomies by default in the weighting dashboard.
Closes #1503
Added: New `ep_weighting_default_enabled_taxonomies` filter. Props @felipeelia and @tott
> Add a new `ep_weighting_default_enabled_taxonomies` filter

- elasticpress.php
- includes/classes/AdminNotices.php
This PR updates versions required for Elasticsearch and WordPress
Closes #2431
Changed: Required versions of WordPress and Elasticsearch
> Update ES and WP required versions

- includes/classes/SyncManager.php
This PR adds $blog_id and $indexable_slug to the `ep_keep_index` filter.
Closes #2289
Added: `$blog_id` and `$indexable_slug` parameters to the `ep_keep_index` filter. Props @felipeelia and @brandwaffle
> Add `$blog_id` and `$indexable_slug` to the `ep_keep_index` filter

- CHANGELOG.md
- includes/classes/Command.php
- readme.txt
Currently, both commands won't output some indices info, as the list is hardcoded in each function. This PR changes the code so it takes advantage of the new `Command::get_index_names()` method introduced in 3.6.4, outputting info of indices of all registered Indexables.
Fixed: WP-CLI `stats` and `status` to output all indices related to ElasticPress. Props @felipeelia
> WP-CLI: stats and status to output all indices info

- includes/classes/Command.php
This is a take over of #2481:
To help when debugging, or otherwise wanting to send arbitrary requests to ElasticSearch, this adds a new request sub-command, that is somewhat similar to the idea of `wp db query` or the like.
For example `wp elasticpress request _cat/indices --method=GET`
Added: WP-CLI `request` command. Props @joehoyle and @felipeelia
> Add a "request" subcommand

- assets/css/dashboard.css
Using the token field for Instant Results facets required enqueuing the edit post stylesheet which introduced a display bug with the background. Additionally, some styles for the Features screen conflicted with the styles of the token field. This PR fixes both issues.
Check the the styles of the Features page appear correct, including padding around the token field, and that the grey background extends to the bottom of the page.
> Fix CSS issues on Features page.

- assets/js/sync.js
- includes/classes/Screen/Sync.php
#2489
Fixed AJAX URL on subsite
> Fix AJAX URL on subsite

- includes/classes/Feature/Search/Synonyms.php
- includes/classes/Upgrades.php
This PR changes the WP_Query to fetch ep-synonyms, getting all synonyms with any post status. It also makes the check a little looser, simply checking it the post count is greater than or equal to 1, in case someone is changing posts_per_page in all queries.
Closes #2516 
Fixed: Synonyms erased when syncing via WP-CLI. Props @felipeelia and @oscarssanchez
> Synonyms: ignore ep-synonym post status

- includes/classes/Indexable/Post/Post.php
In some cases query args like `post__in` that are expected to be array might contain invalid data such as an empty string. An array like `[ '' ]` will not appear as empty when checked with `empty( [ '' ] )` so this update ensures the arrays only contain real values. Database IDs all start from 1 so removing `0` is ok here.
This issue was observed with Yoast SEO adding subqueries for indexables to populate `post__in` parameters, however the index was incomplete. Can also happens in non-production environments where indexables aren't saved to the database.
Prevents ES query errors such as this one:
```
Warning[16-Nov-2021 09:00:26 UTC] PHP Warning:  Error in ElasticSearch request: {"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: empty …
```
> Ensure array query parameters do not contain empty items

- includes/classes/Indexable/Post/SyncManager.php
- tests/php/indexables/TestPost.php
This is to apply the changes merged in #2483 to develop (and 3.6.6)
> Deleting a metadata without passing an object id now updates all associated posts

- includes/classes/Command.php
It seems if you run the following command: wp elasticpress get-indexes on multisite, you will get a list of index names from all sites, even if you have specified a site to not be indexed. 
The site won't actually be indexed, but the command will return how that name would look, regardless.
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
> Bugfix: Check if site is indexable before building index name

- .github/workflows/build-docs.yml
- .github/workflows/push-asset-readme-update.yml
- .github/workflows/push-deploy.yml
Update external GitHub actions to use their latest versions.
Closes #2534
Security: Use most recent external GitHub actions versions. Props @felipeelia and @qazaqstan2025.
> Update GH actions versions

- includes/utils.php
This PR fixes the notice described in #2538 
Closes #2538 
Fixed: PHP Notice while monitoring a WP-CLI sync in the dashboard. Props @felipeelia and @ParhamG.
> Fix notice for undefined $url

- assets/js/instant-results/components/facets/facet.js
- assets/js/instant-results/components/facets/post-type-facet.js
- assets/js/instant-results/components/facets/taxonomy-terms-facet.js
- assets/js/instant-results/components/layout.js
- assets/js/instant-results/components/results/result.js
- includes/classes/Feature/InstantResults/InstantResults.php
When two or more taxonomy facets are added with the same label, such as the core `category` ("Category") taxonomy and the WooCommerce `product_cat` (also "Category") taxonomy, they are not differentiated on the front end. This PR adds the labels for associated post types in parentheses to the headings of taxonomy facets whenever there are other facets with the same label. For example, if both the category taxonomies mentioned above are added they will be displayed as "Category (Posts)" and "Category (Products)", but if only one is present then the post type will be omitted.
I experimented with displaying the post types as little badges next to the headings, like on search results, but it required a bit too much CSS and I was not confident that the appearance would be consistent across …
> Display post types on facets with duplicate labels.

- assets/js/instant-results/components/facets/post-type-facet.js
- assets/js/instant-results/components/facets/price-range-facet.js
- assets/js/instant-results/components/facets/search-term-facet.js
- assets/js/instant-results/components/facets/taxonomy-terms-facet.js
- assets/js/instant-results/components/tools/clear-constraints.js
- assets/js/instant-results/functions.js
- assets/js/instant-results/index.js
- assets/js/instant-results/reducer.js
It's a common practice to create search forms only for particular post types by adding an `input[name="post_type"]` to the search form, often hidden. For example, the WooCommerce product search form has a hidden input named `post_type` with the value `product`, so that only Products are searched. This PR updates Instant Results to automatically apply a post type filter for any post type fields in the search form.
Instant Results will respect any post type filters that have been applied to an existing search form. For example, when submitting the form in the WooCommerce _Product Search_ block/widget or `get_product_search_form()` Instant Results will automatically apply a post type filter so that only Products are searched. If Instant Results is configured with a _Post type_ facet then the …
> Apply post types from search forms to Instant Results as a filter 

- includes/classes/Feature/Comments/Comments.php
- includes/classes/Feature/Search/Search.php
- includes/classes/Feature/Terms/Terms.php
- includes/classes/Feature/Users/Users.php
- includes/classes/Feature/WooCommerce/WooCommerce.php
- includes/classes/Indexable.php
- tests/php/features/TestComments.php
- tests/php/indexables/TestPost.php
- tests/php/indexables/TestTerm.php
- tests/php/indexables/TestUser.php
> Evaluate 0 and false string as false booleans as well

- includes/classes/Feature/InstantResults/InstantResults.php
Currently, [InstantResults::apply_product_visibility()](https://github.com/10up/ElasticPress/blob/4.0.0-beta.1/includes/classes/Feature/InstantResults/InstantResults.php#L474) calls `wc_get_product_visibility_term_ids()` and uses `$product_visibility_terms['exclude-from-search']` as an array, when it actually is a term id. In PHP 8, that results in a fatal error:
> PHP Fatal error:  Uncaught Error: Cannot use a scalar value as an array in /var/www/html/wp-content/plugins/elasticpress/includes/classes/Feature/InstantResults/InstantResults.php:479
This PR addresses that, forcing the result to be an array.
- Spin up a local env using PHP 8
- Install WooCommerce and enable "Hide out of stock items from the catalog" (/wp-admin/admin.php?page=wc-settings&tab=products&section=inventory)
- …
> Fix product visibility evaluation in PHP 8

- tests/php/TestFeatureActivation.php
I'm still not exactly sure why but after WordPress 5.9 was released our PHP Unit tests stopped passing. This PR addresses the needed change to have them working again.
Related to #2555
Fixed PHPUnit tests
> Fix PHP Units after WordPress 5.9

- includes/classes/Feature/Comments/Comments.php
- includes/classes/Feature/Search/Search.php
- includes/classes/Feature/Terms/Terms.php
- includes/classes/Feature/Users/Users.php
- includes/classes/Feature/WooCommerce/WooCommerce.php
- includes/classes/Indexable.php
In #2547 we've introduced a check for different false values while checking if the request should or not be integrated to EP. I have wrongly suggested the usage of `! filter_var( $query->query_vars['ep_integrate'], FILTER_VALIDATE_BOOL )` when that should use the `FILTER_VALIDATE_BOOLEAN` constant.
This PR fixes the wrong constant usage (sorry!)
> Adjust constant name

- includes/classes/Indexable/Post/SyncManager.php
- tests/php/indexables/TestPost.php
Instead of completely wiping out the queue when a post is deleted, this change only removes from the queue the post that was deleted.
Closes #2568
Fixed: Posts insertion and deletion in the same thread.
Props @felipeelia and @tcrsavage
> Only remove from the queue the deleted post

- README.md
- includes/classes/Feature/WooCommerce/WooCommerce.php
This PR removes an adjustment in the `orderby` parameter that EP was doing on WooCommerce queries and is no longer needed. 
In older versions of WC (apparently until [WC 3.0.9](https://github.com/woocommerce/woocommerce/releases/tag/3.0.9), released in June 2017), it was defaulting to `menu_order title => ASC`: https://github.com/woocommerce/woocommerce/blob/3.0.9/includes/class-wc-query.php#L449
Newer versions are already ordering by relevance DESC, as ElasticPress does.
Closes #2473
Changed: to comply with modern WooCommerce behavior, ElasticPress does not change the orderby parameter anymore.
Props @felipeelia and @beazuadmin
> Remove unnecessary order adjustment for WC queries

- includes/classes/Indexable/Post/Post.php
We're noticing that on very large sites, the query to count the total objects in `get_total_objects_for_query()` dies. This PR adds an abstracted helper method `get_total_objects_for_query_from_db()` that breaks it down using `wp_count_posts` to count the posts directly from the DB.
N/A.
A bit more processing during indexing if the count query has died, but at least the user will have an idea of the number of posts, rather than "0".
On a verrrry large site where it says `0` as the total objects, i.e. `Processed x/0`, apply the PR and expect it to return a number.
Fixed: Add an alternative way to count total posts on larger DBs during indexing
Props @rebeccahum
> Add helper get_total_objects_for_query_from_db() which counts directly from the DB

- includes/classes/Indexable/Post/Post.php
Having a tax_query with terms being an array of not valid values results in a broken query.
```
{
"tax_query": [
{
"taxonomy": "category",
"field": "slug",
"terms": [
null
],
"operator": "IN"
},
{
"taxonomy": "category",
"field": "term_id",
"terms": [
1
],
"operator": "NOT IN"
}
]
}
```
=> 400
```
{
"error": {
"root_cause": [
{
"type": "parsing_exception",
"reason": "No value specified for terms query",
"line": 1,
"col": 507
}
],
"type": "parsing_exception",
"reason": "No value specified for terms query",
"line": 1,
"col": 507
}
```
Not sure, this seemed like a most logical place to put it to ensure no invalid terms would ever make it into the final query.
This is still not 100% bulletproof because in even edgier case where a non-empty array or an object instance is passed it would not …
> Fix a rare edge-case bug where invalid values in tax_query terms resulted in a broken query

- assets/js/sync.js
- includes/classes/Screen/Sync.php
> Show WP-CLI progress on sync page

- includes/classes/Indexable/Term/Term.php
This PR removes a duplicate `case 'description':` from `ElasticPress\Indexable\Term\Term::parse_orderby()`.
N/A
Dead code elimination.
N/A
Run the test suite locally.
N/A
Removed a duplicate `case 'description':` from `ElasticPress\Indexable\Term\Term::parse_orderby()`
> Remove duplicate "case 'description'"

- assets/css/instant-results.css
- assets/css/instant-results/checkbox.css
- assets/js/instant-results/components/common/checkbox-list.js
- assets/js/instant-results/components/common/checkbox.js
- assets/js/instant-results/components/facets/post-type-facet.js
- assets/js/instant-results/components/facets/taxonomy-terms-facet.js
Adds result counts for facet options in Instant Results.
Closes #2526.
Design-wise there could be any number of variations, but as the default I stuck with simple numbers in parentheses. To support users and themes styling the counts differently, such as in a bubble or similar, the counts have their own element, and parentheses are added with CSS so that they can be removed with CSS. From testing with VoiceOver there was no difference in accessibility in using CSS for the parentheses.
With this PR the counts are enabled by default, with no setting to choose to enable or disable them, however they occupy their own element so they can be easily hidden with a single line of CSS.
N/A
With this PR checked out the counts should be visible next to filter options in Instant Results. Selecting …
> Displaying results counts for facet options in Instant Results

- includes/classes/Feature/Facets/Widget.php
Adds aria attributes to facets to improve accessibility. This includes adding `aria-disabled` and `aria-role` attributes to disabled links, as per the solution described in [this article](https://www.scottohara.me/blog/2021/05/28/disabled-links.html). It also includes adding an `aria-label` attribute to the links, so that the accessible label makes it clear whether following the link will add or remove the filter.
The change also includes a filter for the accessible label: `ep_facet_widget_term_accessible_label`.
Closes #2596
1. Add a facet widget to a page.
2. Observe the list of links, available facets should have an `aria-label` that reads "Apply filter:", followed by the term name.
3. After applying a filter, observe disabled options, they should have an `aria-disabled="true"` …
> Add aria attributes to improve facet accessibility.

- elasticpress.php
This PR applies a new order to the features screen, so more relevant features are displayed first. This same order will also be applied in the feature selection in the new step of the installation workflow.
This PR does not address the problem for mobile users, where the entire left column will be displayed above the right column. IMHO it is unlikely that admin users are changing features in a mobile screen, so I'd not consider it a blocker for 4.0.
Closes #2606
Changed: Features order in the features screen.
Props @felipeelia @brandwaffle
> Reorder features

- includes/classes/Feature/WooCommerce/WooCommerce.php
- includes/classes/IndexHelper.php
In some points, WooCommerce uses a `search` parameter instead of `s`, so it can search for specific fields. As ElasticPress already accounts for those fields, this PR sets the search term back to `s`, so integration can continue its course.
In addition to that, the PR also removes an indentation level by early returning and fix small issues in the new IndexHelper class.
Closes #2371
Changed: ElasticPress uses WooCommerce's `search` parameter.
Props @felipeelia @dianfishekqi @oscarssanchez
> WooCommerce Integration: `search` parameter

- .github/hookdoc-tmpl/README.md
- .github/workflows/build-docs.yml
- .github/workflows/cypress-tests.yml
- .github/workflows/lint.yml
- .github/workflows/php-compatibility.yml
- .github/workflows/push-asset-readme-update.yml
- .github/workflows/push-deploy.yml
- .github/workflows/test.yml
- CONTRIBUTING.md
- README.md
- SECURITY.md
- docs/install.md
- package.json
- readme.txt
This PR is the first step of #2492, where all the references to the master branch are replaced with "trunk".
It also adds instructions about how to build assets, updates the node required version, and optimize GitHub actions a bit.
Changed: `trunk` is now the repository main branch.
> Node version and replace references to "master" with "trunk"

- includes/classes/IndexHelper.php
Fixed: Logic checking if it is a full sync and if search should go or not through ElasticPress.
Props @felipeelia @JakePT
> Fix put_mapping check and return filtered value

- includes/partials/stats-page.php
Correct the link on the Index Health page when no indexes are found.
Closes #2641.
1. Delete any indexes via WP CLI, `wp elasticpress delete-index`.
2. Visit _ElasticPress > Index Health_.
3. You'll see a message, "We could not find any data for your Elasticsearch indices. Maybe you need to sync your content?". Follow the "sync your content" link.
4. You should be taken to the _ElasticPress > Sync_ page.
> Use correct sync link on index health page

- includes/classes/Feature/InstantResults/InstantResults.php
Changed: Instant Results: type and initial value of search template and move save to the end of sync.
> Adjust search_template type and initial value + move save to end of sync

- includes/classes/Command.php
Problem
- Running `wp elasticpress get-indexes` causes the following PHP warnings:
```console
$ wp elasticpress get-indexes
PHP Warning:  Trying to access array offset on value of type int
in /wp-content/plugins/elasticpress/includes/classes/Command.php on line 427
PHP Warning:  Trying to access array offset on value of type int
in /wp-content/plugins/elasticpress/includes/classes/Command.php on line 430
["active-mysite-post-1"]
```
Cause
- On non-multi-site installations, Command::get_index_names() uses a pseudo list of sites only containing the current/single site. The element in this array matches the expected structure of a [WP_Site](https://developer.wordpress.org/reference/classes/wp_site/), but the outer array for the list is missing.
Proposed solution
1. Fix the array structure to …
> Fixed PHP warning Trying to access array offset on value of type int in get_index_names().

- tests/cypress/integration/features/search/synonyms.spec.js
This PR adds cypress tests related to the Synonyms feature.
Related to #2614
Added: e2e tests for the Synonyms feature.
> Cypress tests for the Synonyms feature

- assets/js/sync.js
This PR improves error handling of the Dashboard Sync by displaying an error message when the admin-ajax calls return invalid JSON data. 
This is what the Sync UI looks like without this fix on the develop branch, when the server returns an invalid JSON response.
And this is what the Sync UI looks on this feature branch with the same invalid JSON response.
To test this PR I created an mu-plugin with the following code. This can also be seen by introducing other output into admin-ajax calls like PHP Warnings, incorrectly output styles, etc.
```php
<?php
add_action( 'admin_init', function() {
if ( ! ( defined( 'DOING_AJAX' ) && DOING_AJAX ) ) {
return; 
}
throw new Exception( 'Exception during Admin AJAX' );
} );
```
Closes #2301
NA
- Create an mu-plugin and copy-paste the above …
> Shows an error message if the server returned invalid json during a Sync

- includes/classes/Feature/InstantResults/InstantResults.php
As discussed on #2650, the query that generates the Elasticsearch search template for Instant Results runs in the context of the user being logged in as an admin. This means that the template generated will be for the query for an administrator, so things like excluding password protected posts will not be applied.
This change sets the current user as anonymous while generating the template to resolve this issue. It also includes a filter to allow developers to set a specific user for whom the template should be generated as.
Closes #2650
The original issue suggested using the `determine_current_user` filter to achieve this, by adding a filter that returns false for the current user during template generation. The problem with this is that it turns out that this filter does not actually …
> Generate search template as anonymous user.

- package-lock.json
Title says it all
Security: Updated `@wordpress/env` from 4.2.2 to 4.4.0, and `minimist` from 1.2.5 to 1.2.6.
> Automatic update using npm audit --fix

- includes/classes/IndexHelper.php
In some cases, IndexHelper will try to output an array of messages related to the same error. This PR takes that array and transforms it back into a string.
- Add the following code to a website:
```
add_filter(
'ep_prepare_meta_data',
function( $post_meta, $post ) {
for ( $i = 0; $i < 100; $i++ ) {
$post_meta[ "test_meta_{$i}_title_{$post->ID}" ] = 'Lorem';
$post_meta[ "test_meta_{$i}_body_{$post->ID}" ]  = 'Ipsum';
}
return $post_meta;
},
10,
2
);
```
Normally, it'd make the index fail due to `[illegal_argument_exception] Limit of total fields [5000] in index [domain-post-1] has been exceeded` error if the user executes `wp elasticpress index --setup --yes --show-errors`. With the code in the PR, the error is properly outputted, instead of silently failing.
Fixed: Handle the output of …
> IndexHelper: handle the output of an array of messages

- includes/classes/Feature/Search/Weighting.php
- tests/php/features/TestWeighting.php
This PR is an alternative version of #2597, changing the approach a little bit and also adding unit tests.
Note that this bug only happens when only fields using `'enabled' => 1` are added, i.e., if default fields are enabled, it will still work properly.
Fixed: Truthy values for the `'enabled'` field's attribute while using the `ep_weighting_configuration_for_search` filter.
Props @felipeelia and @moritzlang
> Allow truthy values for enabling weighting

- includes/classes/Indexable/Post/Post.php
- tests/php/indexables/TestPost.php
Currently, the plugin only supports a single array as the `aggs` parameter of WP_Query. This PR changes that to also support an array of aggregations. This will be needed to implement #1440 in a cleaner way.
Closes #636
Added: Support for an array of aggregations in the `aggs` parameter of WP_Query.
> Add support for multiple aggregations
