- classes/class-ep-wp-query-integration.php
- tests/test-single-site.php
Add tests for excluding post types from search. Fix for returning early to ensure found_posts is properly calculated
Ready for review/merge @tlovett1
> Add tests for exclude from search, fix minor bug in calculating found_posts

- bin/wp-cli.php
Add functionality to stats method for displaying info for all sites on a multisite network.
> Refactor wp-cli stats for multisite

- classes/class-ep-api.php
- tests/test-multisite.php
fixed day of week for sync and updated unit tests accordingly
> fixed day of week for sync, updated unit tests

- tests/bootstrap.php
Added some data sanitization so the plugin will pass PHP Code Sniffer scans for the GovLoop Academy project.
> Sanitization Updates

- README.md
- bin/wp-cli.php
> Revert "Add --offset paramater to cli index command"

- bin/wp-cli.php
> Delete the error email for failed posts

- classes/class-ep-api.php
> #283 add a filter to modify request header

- classes/class-ep-api.php
Fixes #286 
@tlovett1 #reviewmerge
> Improve error reporting for bad responses from ES server

- classes/class-ep-config.php
- classes/class-ep-sync-manager.php
- tests/test-single-site.php
Simple PR to enable indexing of attachments.
> Enable indexing of attachments

- classes/class-ep-api.php
- tests/test-single-site.php
> Fixed #304 allow recursively terms indexing

- tests/test-single-site.php
> Make tests PHP 5.2 compat

- classes/class-ep-wp-query-integration.php
One new filter has been added: `ep_wp_query_search_cached_posts`
If `ep_wp_query_search_cached_posts` returns posts, then search will use those instead of pinging ES.
One new action has been added: `ep_wp_query_non_cached_search`. This fires when an uncached search is ran. This is where you would hook into save data to your cache.
> Support post caching in search

- classes/class-ep-config.php
- tests/includes/class-ep-test-base.php
- tests/test-single-site.php
Removing public for indexable, adding another assertion for unit test……. fixes 321
> Issue #321 - exclude_from_search

- classes/class-ep-api.php
- classes/class-ep-wp-query-integration.php
- includes/mappings.php
As we now support attachment indexing, allowing guid to be indexed and
retrieved is crucial as this field is utilised in media screen to
display file name.
Making a PR for @tuanmh
> Allow guid to be index and retrieved

- classes/class-ep-api.php
- tests/test-single-site.php
Wasn't sure what to put for `@since` but I can tweak it before merge or you can do it after.
> Add support for post__in and post__not_in

- classes/class-ep-api.php
Great for debugging purposes
Fixes #326
> Add ep_index_post_retrieve_raw_response action to EP_API::index_post()

- classes/class-ep-api.php
- tests/test-single-site.php
This is similar to #328 and based off @sc0ttkclark 's code but does not include any default private fields to index.
> Adds a filter to allow the indexing of specified private meta keys.

- classes/class-ep-api.php
- tests/test-single-site.php
> Fix posts_per_page typo, keeping backwards compatibility

- bin/wp-cli.php
I missed a use case on the last one that wasn't apparent until trying to index a very large site. Namely, when a post was "killed" we would instantly return out of the queue function. The problem here is if the LAST post on a site was killed. In this case because we already left the queue function we would never trigger the bulk index. To make matters worse it also would never reset the post count resulting in all subsequent processing across any site not yet synced would also fail.
This patch moved the exit of the queue back and sets a status still processing posts if the count is right regardless of whether the current post was killed.
> Always process when needed

- classes/class-ep-sync-manager.php
> Still sync on publish/update when doing cron

- bin/wp-cli.php
- classes/class-ep-api.php
I do believe this will address #367. Need to test with some better data however.
> Use wp_json functions for encoding and decoding

- classes/class-ep-api.php
- classes/class-ep-sync-manager.php
- tests/test-multisite.php
Also includes additional unit tests when removing indexes
> Remove index of sites marked as spam

- classes/class-ep-api.php
Allows search request path to be updated for including things like shard preference to account for custom sorting differences between shards.
> Allow modifications to search request path

- classes/class-ep-api.php
> (Closes #414) Avoid Elasticsearch returning error 404 during post deletion

- classes/class-ep-api.php
> Look in query_vars instead of query to determine enabled status.

- elasticpress.php
When I try to create language pack for this plugin, realized that language packs couldn't load correctly.
> localization problem fixed

- classes/class-ep-api.php
- includes/mappings.php
This makes it much easier for people/plugins trying to order by ID.
> Add ID field to mapping

- classes/class-ep-api.php
- tests/test-single-site.php
Title says it all. Right now we just support `and`.
> Support OR relation for tax_query

- classes/class-ep-index-status.php
In our case, we don't really need to show this index status to our users, except administrators, this filter will does the job.
> Filter to not print out post index status

- classes/class-ep-api.php
- tests/test-single-site.php
> Support meta between query with tests

- bin/wp-cli.php
- classes/class-ep-index-gui.php
- classes/class-ep-index-worker.php
A couple extra hooks during CLI and GUI syncing.
> Add post index/put mapping hooks

- bin/wp-cli.php
Simple fix that was messing with WPML.
> Make sure post_type array isn't associative in CLI index

- classes/class-ep-api.php
- tests/test-single-site.php
> Add support for query by post_status

- classes/class-ep-api.php
- tests/test-single-site.php
This reverts commit aded699972fd87fcbc41312770feb5c9caece724.
> Revert "Revert "Add support for tax_query NOT IN operator""

- modules/search/search.php
- tests/test-single-site.php
> Set search fields which are provided in query arguments otherwise set default search fields for Elasticsearch query

- modules/woocommerce/woocommerce.php
> Do not add any WooCommerce related action/filter if WooCommerce is not active

- classes/class-ep-api.php
> Add ep_search function for backward compatibility

- classes/class-ep-api.php
> Fix admin integration does not work when searching

- modules/woocommerce/woocommerce.php
> Fix Conflict with WooCommerce PDF Invoices & Packing Slips

- classes/class-ep-sync-manager.php
> Abort action queue meta sync if EP is not alive

- modules/related-posts/related-posts.php
> Fix: when only related posts module is active, it does not work

- classes/class-ep-sync-manager.php
and trim whitespace, because that's what my editor is config'ed to do
> replace deprecated function

- classes/class-ep-api.php
Fix for issue https://github.com/10up/ElasticPress/issues/634
> (Closes #634) Fix aggregation value

- bin/wp-cli.php
> Fix CLI commands to list/activate/deactivate features

- bin/wp-cli.php
> Making stop_the_insanity method compatible with WordPress 4.7

- bin/wp-cli.php
> fix error indexing with pagination fix #714

- classes/class-ep-api.php
> disable oembed while indexing which cause fatal error

- features/woocommerce/woocommerce.php
> honor ep_integrate when set in WP_Query

- classes/class-ep-config.php
- classes/class-ep-dashboard.php
- lang/elasticpress.pot
I update the word occuring to occurring. This is a typo that should be fixed.
> Fix(spelling): The word Occuring is not spelled right.

- classes/class-ep-api.php
- features/woocommerce/woocommerce.php
> add sanity check for taxonomy in prepare_terms

- classes/class-ep-dashboard.php
- features/protected-content/protected-content.php
- includes/dashboard-page.php
- includes/settings-page.php
> #931 - Late escaping per WordPress.com VIP review

- .travis.yml
- classes/class-ep-api.php
- elasticpress.php
> Support for ES 5.5.x and strict content type checking

- classes/class-ep-features.php
Fixed #854 
I did run few tests on feature activations, run unit testing and try some search and WP_Query. Seems okay.
But still need some more testing before we merge this
> moved setup_feature on init

- classes/class-ep-config.php
Reverts 10up/ElasticPress#1007
> Revert "Added inherit status to support attachments indexing."

- classes/class-ep-dashboard.php
- lang/elasticpress.pot
- readme.txt
- tests/test-admin-notifications.php
fix typos OK?  remove trailing whitespace OK?
> Propose fix typos

- classes/class-ep-api.php
> Fix #1045 - TRUE in  terminates ep_query process when it shouldn't

- features/autosuggest/autosuggest.php
> type = "text" not suppported in older ES

- classes/class-ep-api.php
Reverts 10up/ElasticPress#1094
> Revert "Exclude password protected posts in search results. "

- classes/class-ep-api.php
Add ep_set_default_sort filter to orderby to enable changing the sort order by score.
> Add ep_set_default_sort filter to orderby

- classes/class-ep-api.php
- tests/test-single-site.php
fix #893
This PR is to add support for EXISTS and NOT EXISTS operator for tax_query.
Also added the unit testing
> Add support for tax_query operator EXISTS and NOT EXISTS

- features/woocommerce/woocommerce.php
> Allow the autosuggest feature to suggest WooCommerce products 

- classes/class-ep-config.php
- classes/class-ep-dashboard.php
- includes/settings-page.php
Allow index prefix to be configured on settings page instead of just within wp-config.php.
> Configure Index Prefix on Settings Page

- classes/class-ep-api.php
- classes/class-ep-sync-manager.php
Add additional hook for when an blog is deleted.  Also conditional logic to prevent posts from getting indexed if blog is not indexable.
> Prevent indexing when blog is deleted or not public

- classes/class-ep-api.php
Reverts 10up/ElasticPress#1167
> Revert "Use wildcard query with compare like."

- features/autosuggest/autosuggest.php
- features/documents/documents.php
Feature color changes when properly activated on elasticpress.io service.
> Feature Colors When Active

- classes/class-ep-api.php
Reverts 10up/ElasticPress#1210
> Revert "Revert "Use wildcard query with compare like.""

- bin/wp-cli.php
When calling `wp elasticpress status` or `wp elasticpress stats` the call is to the root of ES server. These calls can fail in shared environments depending on how they are configured. This PR modifies the requests so that they include all indices as part of the request.
Is not tested on large multisite installs.
> send index names as part of _recovery or _stats request

- includes/settings-page.php
Add elasticsearch version in settings.
Related Issue #1176
Let me know if this make sense o if we need other information about ES in settings page.
> Add elasticsearch version in settings.

- README.md
Hi @allan23 ,
Could you please review the wording/place used to add supported ElasticSearch documentation in the README ? Addresses #1213 
Thanks!
> Add ES max version supported

- classes/class-ep-api.php
- features/autosuggest/autosuggest.php
This corrects an issue with sticky posts altering homepage queries.
> Changes to sticky posts

- README.md
Hi @allan23 
Could you please take a look at this PR when you have time? Per Vasken comment, I moved the ES max supported version to the requirements section. I also corrected an issue spotted on the WP-CLI apartment. 
Thanks!
> 3.0 README fixes

- includes/partials/settings-page.php
Redo https://github.com/10up/ElasticPress/pull/1255 for ElasticPress 3.0.
Issue: https://github.com/10up/ElasticPress/issues/1254
> Redo adding hook for EP3

- classes/class-ep-wp-query-integration.php
Per #1265, the REST API fails to return search queries due to found_posts returning a null value.
> Addition of found_posts filter

- README.md
After updating to 3.0 the function ep_find_related() seems to be gone. But its still referenced under Features in the README.md
Should also be mentioned in the changelog because otherwise it will throw a Uncaught Error: Call to undefined function ep_find_related()
ep_find_related removed from the readme
ep_find_related could be preserved and just call the Feature class.
Prevent confusion
> ep_find_related is gone

- phpcs.xml
> Add phpcs xml file

- includes/classes/Feature/Autosuggest/Autosuggest.php
- includes/classes/Indexable/Post/Post.php
- includes/dashboard.php
- includes/partials/dashboard-page.php
- readme.txt
PHPCS fixes and a new kses context.
> PHPCS fixes

- includes/classes/Indexable/Post/Post.php
Fixes #1336
`Use \WP_User as WP_User` so the `instanceof WP_User` check works as expected.
> Fix bug with indexing author data for Posts

- includes/classes/Indexable.php
- This PR adds the possibility to filter the bulk index action/metadata arguments.
- When working with the join/relation field we need to route the child to the same shard as the parent. When index one by one we can achieve this by adding the `?routing` argument. As this is not working with the Bulk API we need to define the routing in the action/metadata line per document.
- Potential performance drawbacks due to new hook registration and another `wp_json_encode` function call
Tested by register a new filter:
```php
add_filter('ep_bulk_index_action_args', function ($args, $document) {
if (!empty($document['post_parent'])) {
$args['index']['routing'] = $document['post_parent'];
}
return $args;
}, 10, 2);
```
```
$ wp elasticpress index --post-ids=126284,125924 --setup
GET /myindex/_search …
```
> Added filter for bulk index action args.

- includes/classes/Feature/Facets/Facets.php
Hi @allan23 can you please review and test this PR? 
This PR fixes #1292 by deleting the /page from the displayed URL's of the facet widget. It makes sense to redirect users to page one every time they switch from facets, or when they are on page X of an archive but want to facet their search
Fixes #1292 
Might need more testing
> Delete pagination from facet URL

- includes/classes/Feature/RelatedPosts/RelatedPosts.php
Hi @allan23 
This PR adds filters for the MLT query used in related posts, per documentation : https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html
Giving the developers the ability to control these parameters can improve the precision of the related posts feature for their specific use cases. Fix for #1274 
- [x ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ x] My code follows the code style of this project.
> Add filters to control MLT related posts params 

- CHANGELOG.md
- LICENSE.md
- README.md
This change adds some standard 10up open source details to the repo.
none.
Provides a similar experience for users coming to any 10up open source repo.
none identified.
Manually verified via GitHub web UI.
Resolves #1381.
> Documentation updates

- elasticpress.php
- includes/classes/Elasticsearch.php
- includes/classes/Feature/Autosuggest/Autosuggest.php
- includes/classes/Indexable/Post/Post.php
- includes/classes/Indexable/Post/QueryIntegration.php
- includes/classes/Indexable/User/QueryIntegration.php
- includes/classes/Indexable/User/User.php
- includes/mappings/post/7-0.php
- includes/mappings/user/7-0.php
This PR adds functionality to EP to make it compat with ES 7.0. CC @cmmarslender @brandwaffle
> Support ES 7.0+

- readme.txt
@brandwaffle noted that the Facets portion of the readme.txt file had the same description as the Autosuggest section.  Turns out that's not _quite_ right, so this updates the description to match what's in the readme.md file.
n/a
Correct descriptions will now be shown on WordPress.org.
none identified.
Manually verified via GitHub web UI.
n/a
> Update readme.txt to match readme.md

- package-lock.json
> Update vulnerable npm dependencies

- composer.json
- composer.lock
- includes/classes/Feature/Search/Weighting.php
- includes/classes/Feature/SearchOrdering/SearchOrdering.php
- tests/features/TestSearch.php
- tests/indexables/TestPost.php
Updates tests and/or code to make sure all tests are passing
> Fix Unit Tests

- includes/classes/Elasticsearch.php
Add a missing filter to Elasticsearch query method. Fixes #1433
> Add ep_es_query_results filter

- includes/classes/Feature/Search/Weighting.php
This PR fixes #1431 . Previously the plugin did not have a way to know which fields were previously disabled, by using `array_replace_recursive()` and merging the previous state with the new changes on save, the previous settings are not getting lost as they used to. Also removed `post.author.login` field when author is disabled from the UI, as this was getting injected always as part of Post::format_args() before the weighting engine was released.
1.- Go to settings and disable/enable desired fields.
2..- Add desired weights and save settings
3.- Using the debug bar, check the disabled fields are not in the query body args sent to Elasticsearch, as well as check the enabled ones are sent with proper specified weight.
> Fixes diverse issues with search fields

- includes/classes/Elasticsearch.php
- includes/mappings/post/5-0.php
- includes/mappings/post/5-2.php
- includes/mappings/post/7-0.php
- includes/mappings/post/pre-5-0.php
- includes/mappings/user/7-0.php
- includes/mappings/user/initial.php
- includes/mappings/user/pre-5-0.php
This PR fixes #1403 . The changes are simply to take back the code removed on 2.8 to keep the backwards compatibility.
1.- Ensure ep_default_index_number_of_replicas filter works properly
2.- Ensure ep_default_index_number_of_shards filter works properly
> Bring back shards and replica filters

- includes/classes/Feature/RelatedPosts/RelatedPosts.php
- includes/classes/Feature/Search/Weighting.php
- includes/classes/SyncManager.php
- includes/mappings/post/pre-5-0.php
> Fix phpcs issues

- README.md
- elasticpress.php
README update: bumps documented supported version of ES from 1.7 to 5.0+
As a result of this [weighting issue](https://github.com/10up/ElasticPress/issues/1432), it's clear we need to adjust what is officially supported.
https://github.com/10up/ElasticPress/issues/1432
> bump ES officially supported version to 5.x

- includes/utils.php
> Check wpcli transient before integrating with queries

- composer.json
This moves phpunit to be a development dependency.
> Move phpunit to dev dependencies

- includes/dashboard.php
- Hooking the cache clearing function to admin_init as only here the screen logic can be used.
- Adding the install screen to the logic for clearing the cache.
> This addresses #1466

- includes/classes/Feature/Search/Weighting.php
Caused with combination of weighting and custom ordering
> Remove empty fields arrays

- includes/classes/Feature/SearchOrdering/SearchOrdering.php
This PR adds better admin messages for the custom result post type and properly uses the esc_html version on localization functions.
> Improve messaging for custom result post type

- includes/classes/Indexable/Post/Post.php
- tests/indexables/TestPost.php
This PR adds compatibility for `tag__and` and `tag_in` as requested on #1426 by querying elasticsearch` terms.post_tag.term_id` field.
In the case of tag_id, make sure it is always an singular value as described on https://developer.wordpress.org/reference/classes/wp_query/#tag-parameters
> tag_id (int) – use tag id.
And for tag__and, providing a single value or array should be acceptable:
> tag__and (array) – use tag ids.
> Add tag_in and tag__and support

- includes/classes/Feature/RelatedPosts/RelatedPosts.php
It looks like https://github.com/10up/ElasticPress/pull/1506 left out enqueuing the block assets on the frontend and the block was not showing anymore. This PR fixes this by hooking into `enqueue_block_assets`
> Enqueue block assets on the frontend

- includes/classes/Feature/Autosuggest/Autosuggest.php
This PR fixes the edge case outlined in #1554 where the query used to build the autosuggest query would fall back to the database in case of any error which would occur. This PR fixes this behavior by ensuring an empty posts array is returned at any case.
> Ensure query building for Autosuggest does not fallback to WPDB

- README.md
readme.txt has already been bumped to 5.3, this updates the repo badge to match
none
Avoids confusion for folks viewing the GH repo to determine the WP version tested up to.
none identified
Manually verified via GitHub web UI.
n/a
n/a
> bump tested-up-to badge to 5.3

- includes/classes/Elasticsearch.php
Fix ES 7 delete, index, and get document.
> Fix index, delete, and get document

- includes/classes/Indexable/User/User.php
- tests/php/indexables/TestUser.php
> User query number should default to -1

- includes/classes/Elasticsearch.php
Readd `ep_retrieve_aggregations` hook for backwards compatibility. Fixes #1493
> Readd ep_retrieve_aggregations hook for backwards compat

- docs/install.md
> Update max supported version of ES

- includes/classes/Indexable/Post/Post.php
- includes/classes/Indexable/User/User.php
PR creates an easier way to filter the final list of meta stored in ES.
> Add ep_prepared_*_meta filters

- includes/classes/Indexable/Post/Post.php
Cast taxonomy slug to array in case it's already an array
> Cast taxonomy slug to array in case it's already an array

- includes/classes/Command.php
There are a few places we are checking `--network-wide` when we should be checking `EP_IS_NETWORK` (see #1496). This refactors that logic. Network wide is only needed in indexing, put mapping, and deleting index(es).
To test, all CLI functions should be tested with and without network wide as well as network activated and not network activated.
#1496
> Rethink usage of network-wide CLI argument

- includes/classes/Indexable/User/User.php
Add `nickname`, `display_name`, `first_name`, and `last_name` to user search fields.
> Add name, nickname, and display name to user search

- composer.lock
- tests/php/includes/functions.php
- tests/wpa/BasicTest.php
This PR fixes existent WP Acceptance errors. Right now we have some tests leaving behind some setting changes and that is interfering in subsequent tests.
n/a
WP Acceptance tests passing again.
n/a
Run './vendor/bin/wpacceptance run'
Relates to #1693 
n/a
> Fix existent WP Acceptance Tests

- includes/classes/Indexable/Term/Term.php
- tests/php/indexables/TestTerm.php
* Increased the code coverage on the \ElasticPress\Indexable\Term\Term class to 100%
Improved unit tests
None
Verified all existing unit tests passed
None
None
> Expanded indexable term test coverage

- .github/workflows/build-docs.yml
We currently update the hookdoc site when commits happen to develop, but given that code is not yet released the hookdoc site may not reflect the actual plugin hooks.  This PR switches to updating the hookdoc site when commits happen to master which should better ensure that what appears on the hookdoc site reflects the actual hooks in the plugin.
Keep as-is
Reduces chances for mismatch between plugin hooks and what's noted on our hook docs site.
None identified.
Manually verified via the GitHub web UI.
n/a
n/a
> Switch to building docs on push to master

- .travis.yml
We're using one job for linting, wpa and unit test. These three tasks are run in sequence and it's hard to check which test causes the build fails when it happens.
This PR split the testing stage into 3 jobs. This makes the test run faster because jobs are run in parallel. In addition, it's easier to see which test is failed and easier to trigger the build manually that targets only one test suite.
See Travis passes.
> CI: Use Travis jobs to speed up testing process

- tests/php/features/TestAutosuggest.php
Increase test coverage for `Feature/Autosuggest` (78.79% lines). There are some parts of the codebase using `Utils\is_epio()` left untouched.
> Autosuggest unit test coverage

- docs/feature-api.md
Since EP 3.0, the Feature API has changed. This PR updates the documentation related to that.
n/a
Updated Docs <3
n/a
Previewed on VS Code and GitHub Preview.
#1761
n/a
> [Docs] Update the Feature API page

- includes/classes/Feature/Facets/Facets.php
> More specific GET param check. Fixes #1826

- includes/classes/Installer.php
- includes/dashboard.php
- includes/partials/install-page.php
- uninstall.php
This adds a link to the install page that allows people to skip the install.
> Skip install

- includes/classes/AdminNotices.php
The `get_registered_feature` method can return boolean `false`, so in that case, calling `is_active()` on this value will cause an error:
```Uncaught Error: Call to a member function is_active() on boolean in /usr/src/app/vendor/10up/elasticpress/includes/classes/AdminNotices.php on line 84
process_using_autosuggest_defaults_notice()
call_user_func()
vendor/10up/elasticpress/includes/classes/AdminNotices.php:63
process_notices()
vendor/10up/elasticpress/includes/dashboard.php:302
ElasticPress\D\maybe_notice()
wp-includes/class-wp-hook.php:287
apply_filters()
wp-includes/class-wp-hook.php:311
do_action()
wp-includes/plugin.php:478
do_action()
wp-admin/admin-header.php:267
require_once()
wp-admin/network/index.php:65
```
It will fix a bug 
none
There is no error message at …
> Type check $feature before using method

- README.md
- elasticpress.php
Hi @tlovett1 ,
Could you please review this PR? This bumps the EP_ES_VERSION_MAX to 7.9 and updates the readme to account for this change.
Unit tests seem to pass with the exception of synonyms but it looks like this is an error with these tests and not related to 7.9:
On manual testing, all features worked correctly and no errors showed on the debug bar.
Add official support for 7.9
> Bump EP Max Version to 7.9

- includes/classes/Feature/Documents/Documents.php
Hi @tlovett1 ,
Could you please review this PR? 
This adds a check to see if elastisearch request returns the ES version, and if it doesn't, skip the next check (ES plugins). It looks like if your ES goes off for any reason (the case that brought this was a timeout from indexing documents) your documents feature will deactivate automatically. 
I think the check should only happen if ES is online and then check if we indeed have the ingest attachment plugin. This seems to solve the issue for the client who brought this to our attention as well.
> Return status early if elasticsearch not available

- CHANGELOG.md
This PR adds links for releases in the CHANGELOG.md footer so that each release section properly links to the changes between that release and the one prior.
n/a
Ensures anyone wanting to inspect specific commits within a release has an easy link to view those.
none identified
Manually verified each link showed correct commit changes for each release.
n/a
n/a
> add release links to CHANGELOG.md

- includes/classes/Feature/Search/Highlighting.php
> Only highlight search terms on the front end

- includes/classes/AdminNotices.php
Hi @tlovett1 ,
This PR simply corrects this autosuggest notice:
In favor of this one: `Autosuggest feature is enabled. If documents feature is enabled, your media will also become searchable in the frontend.`
As the safe values option was removed from autosuggest settings.
Less confusion with autosuggest.
> Correct autosuggest notice

- includes/classes/Feature/SearchOrdering/SearchOrdering.php
> Remove quick and bulk edit from custom search results post type

- includes/utils.php
This PR fixes #1810 by replace `+` with `array_merge`.
`+` will combine items with same numeric keys but `array_merge` doesn't.
n/a
Allows facet to work with 3 or more levels depth taxonomies.
None that I'm aware of.
See #1810.
Fixes #1810
> Fix: Facet Widget & 3-level deep hierarchical taxonomy

- includes/classes/Command.php
This PR fixes the network alias creation, checking if the site is really indexable. Right now, it fails when we have an archived site in the network.
> WP-CLI: Create alias just for indexable sites in the network

- includes/classes/Indexable/Post/Post.php
Switch to new search algorithm. The new algorithm uses a phrase match and another phrase match with slop 5. This is much more precise than the current algorithm. I've added a filter that people can use to revert back to the old algorithm.
> More precise search algorithm

- CHANGELOG.md
- README.md
- readme.txt
Otherwise apply_filters generates a PHP Notice:
```
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function '3.4' not found or invalid function name in /var/www/html/wp-includes/class-wp-hook.php on line 287
```
> Improves the recommendation about how to use the old algorithm

- includes/classes/Feature/Search/Synonyms.php
Resets array keys when adding analyzer filters so that json encoding interprets the map as a flat array rather than a keyed map.
> Reset array indexes when adding analyzer filters

- includes/classes/Feature/Search/Synonyms.php
> Improve error messages when updating synonyms fail

- README.md
`readme.txt` already claims 5.6, this updates `README.md` accordingly.
n/a
Ensures we display accurate tested-up-to values in the GitHub-default `README.md` file.
none identified
Manually verified via GitHub web UI.
n/a
n/a
> bump WP tested-up-to 5.6 in README.md

- includes/classes/Indexable.php
An action that fires after each bulk indexing operation. 
N/A
Allows actions to be performed after a bulk indexing operation. Useful for handling errors / issues.
N/A
We needed a way to handle failures gracefully and not drop changes unintentionally. After this change, we could gracefully handle errors and not drop changes unintentionally.
Added ep_after_bulk_index action.
> Added action that fires after bulk indexing

- includes/classes/Indexable.php
Added an action in the form of `ep_delete_{indexable slug}` when a document is deleted.
Props @nickdaugherty
cc: @rinatkhaziev @pschoffer @netsuso @parkcityj
N/A
Allows actions to be done prior to a document being deleted.
N/A
We needed a way to perform actions prior to document deletions. After this change, this was easy and effective.
Added action ep_delete_{indexable slug}. Props @nickdaugherty
> Added action that fires before an object is deleted

- includes/classes/Indexable/Post/SyncManager.php
Allows skipping a sync that's triggered by meta changes. This is used for allow list functionality we added to our search offering.
cc @rinatkhaziev @pschoffer @netsuso @parkcityj
N/A
Provides an easy way to skip syncing on post meta changes for any reason. Whether it be due to allow lists or rate limiting or anything else.
Could accidentally end up skipping post meta syncs if it's set incorrectly.
Prior to the PR, syncing on post meta changes couldn't be skipped. After applying the PR, skipping on post meta syncs was possible.
Added ep_skip_post_meta_sync filter to allow skipping post syncing on post meta changes.
> Add ep_skip_post_meta_sync filter

- includes/classes/SyncManager.php
A filter to allow intercepting the sync process. An example use case for this would be to offload indexing operations to a queue for ratelimiting or to offload large indexing operations to a separate queue for async processing.
Props @nickdaugherty
cc: @rinatkhaziev @pschoffer @netsuso @parkcityj
N/A
Allows stopping indexing before it begins for any reason.
Could allow indexing to be unintentionally prevented. 
We needed a way to prevent indexing in certain scenarios. After applying this PR, it was very easy and we could apply ratelimting and offloading using ElasticPress.
Added pre_ep_index_sync_queue filter. Props @nickdaugherty
> Added pre_ep_index_sync_queue filter

- includes/classes/SyncManager.php
Added a `remove_from_queue` function to the `SyncManager` to prevent extraneous indexing in case of deletions or other situations.
Props @nickdaugherty
N/A
Allows items to be removed from the `SyncManager` queue for any reason.
Manually managing the queue could be inefficient in certain scenarios.
We needed a way to remove items from the queue in certain situations. After applying this PR, this was now very easy.
Added remove_from_queue to SyncManager. Props @nickdaugherty
> Added SyncManager::remove_from_queue

- includes/classes/Feature/Facets/Facets.php
We noticed the size for taxonomies in facets was incredibly large and was having a negative performance impact. So we added a filter to allow this to be lowered.
Props @nickdaugherty
N/A
Allows the direct setting for the taxonomy size for facets so it can be lowered or raised as the situation demands.
Could be set too low or too high resulting in issues.
Before the change the taxonomies size for facets were much too high and caused some issues. After the change we could lower it and the issues went away.
Added ep_facet_taxonomies_size filter to facet queries. Props @nickdaugherty
> Add filter to set taxonomies size in facets

- includes/classes/Feature/WooCommerce/WooCommerce.php
Hi @tlovett1 ,
Can you please review this PR? It looks like by unsetting `$args['query']['bool']['should']` when we want to reassign the search params later here:
`$args['query']['bool']['must'][1]['bool']                               = $args['query']['bool'];`
`$args['query']['bool']` would be equal to the content of this array: 
`$args['query']['bool']['must']`
But what we want to do is keep the search params intact so that we can search by price, but based on a given search term. We had a client who needed the price filtering and this solves their issue.
> Fixes current price filter query unsetting old query 

- includes/classes/AdminNotices.php
- includes/classes/Elasticsearch.php
- includes/classes/Feature/Autosuggest/Autosuggest.php
- includes/classes/Feature/Search/Search.php
- includes/classes/Feature/SearchOrdering/SearchOrdering.php
- includes/classes/Feature/WooCommerce/WooCommerce.php
- includes/classes/Indexable.php
- includes/classes/Indexable/Post/SyncManager.php
- includes/classes/Indexable/User/User.php
- includes/classes/Screen.php
Some adjustments in the code to make linter pass again
> Some lint fixes

- includes/classes/SyncManager.php
Small fix to the docs for the new `pre_ep_index_sync_queue`
> Adjust pre_ep_index_sync_queue docs

- CHANGELOG.md
- elasticpress.php
- package.json
- readme.txt
> prep 3.5.3 for release

- CONTRIBUTING.md
This is just a small addition to the _Release instructions_ list.
> Release instructions: add check for $reindex_versions

- .github/workflows/test.yml
The previous code was pointing to a non-existent trunk branch
> Make tests run when code is pushed to master

- CONTRIBUTING.md
This PR attempts to further clarify the git actions to take during a "normal" release process as well as help define the steps to take for a "hotfix" release as discussed with @brandwaffle.  It would help to have others read through the hotfix instructions to see if they make sense, are concise, and as simple and reasonable as we can make them for these sort of emergent scenarios.
n/a
Ensures we provide those releasing ElasticPress with reliable, repeatable steps to take so as to avoid human error in the release process.
none identified.
Manually verified via VS Code and GitHub Desktop UI.
n/a
```
- Documentation updates (props @jeffpaul @brandwaffle).
```
> Update release instructions, add hotfix release instructions

- SECURITY.md
This PR adds the security issue from 3.5.2-3.5.3 to our Security Policy.  We may want to consider updating the `Supported Versions` section as I'm not 100% certain that's accurate, will defer to @brandwaffle on that.
n/a
Ensures we properly document known issues.
None identified.
Manually verified by the GitHub web UI.
n/a
```
- CSRF Nonce Bypass issue to `Known Vulnerabilities` section of [ElasticPress' Security Policy](https://github.com/10up/ElasticPress/security/policy) (props @jeffpaul).
```
> add security issue from 3.5.4 release to SECURITY.md

- .github/workflows/test.yml
- tests/wpa/BasicTest.php
- tests/wpa/DashboardSyncTest.php
- tests/wpa/features/ProtectedContentTest.php
- tests/wpa/test-mu-plugins/unique-index-name.php
Some small tweaks in the WP Acceptance Tests. It also runs tests against local and EP.io in parallel.
> Small improvements in the WPA tests

- includes/classes/Indexable/Post/Post.php
> Update the ep_search_fields filter documentation

- includes/classes/Elasticsearch.php
When indexing with the CLI, if the `--nobulk` is set, Documents are not ingested by ElatiscSearch. 
Uploading the [pdf-file.pdf](https://github.com/10up/ElasticPress/blob/develop/tests/wpa/test-docs/pdf-file.pdf) and running `wp elasticpress index --nobulk`, the document is indexed with base64 data.
However, running `wp elasticpress index` or `wp elasticpress index --per-page=1`, the document is indexed correctly.
This change applies a filter to change the request path if processing attachment including.
Documents will be indexed correctly with `--nobulk` option.
This has been tested manually:
1. Uploading a [PDF file](https://github.com/10up/ElasticPress/blob/develop/tests/wpa/test-docs/pdf-file.pdf) to Media library
2. Running `wp elasticpress index --nobulk`
3. After indexing, running …
> Apply a filter to change request path if processing attachment

- includes/classes/Indexable/Term/Term.php
Closes: #2044 
Fixed no mapping found for [name.sortable] for Elasticsearch version 5.
> Update to use name.raw instead of name.sortable for version 5.x

- CHANGELOG.md
- elasticpress.php
- includes/classes/Feature/Search/Search.php
- package.json
- readme.txt
> Prep release 3.5.6

- package-lock.json
> Update one ref to socket.io-parser

- readme.txt
> Add captions to WP.org screenshots

- run-wpacceptance.sh
- tests/wpa/features/DocumentTest.php
- tests/wpa/features/RelatedPostsTest.php
- tests/wpa/inc/TestBase.php
> Fix WP Acceptance tests

- includes/classes/Indexable/Post/Post.php
Just expanding docs for the new `ep_set_sort` filter, introduced by #2343.
> Expand docs for ep_set_sort

- includes/classes/Feature/ProtectedContent/ProtectedContent.php
- includes/classes/Indexable/Comment/SyncManager.php
> Fix comment statuses when Protected Content is enabled

- README.md
> Update readme.md to include reference to the support page

- composer.json
- composer.lock
> Add yoast/phpunit-polyfills as a dev dependency

- package-lock.json
- package.json
> Update 10up toolkit

- includes/classes/Feature/InstantResults/InstantResults.php
> Instant Results: Add link to the PHP proxy

- includes/classes/Feature/Search/Weighting.php
- includes/classes/Indexable/Post/Post.php
This PR introduces a new search algorithm, to be the default starting on 4.0.0.
It follows this prioritization
- Exact matches
- Matches in the same field
- Matches across different fields
Added: New search algorithm. Props @brandwaffle and @felipeelia
> New search algorithm

- README.md
- readme.txt
Simply adds or changes notices related to EP 4 Beta 1
> ElasticPress 4.0 Beta 1 Notice

- .eslintrc.js
- .github/workflows/lint.yml
- .github/workflows/php-compatibility.yml
- assets/js/autosuggest.js
- assets/js/comments.js
- assets/js/facets.js
- assets/js/synonyms/components/editors/AlternativesEditor.js
- assets/js/synonyms/components/editors/SetsEditor.js
- assets/js/synonyms/components/shared/LinkedMultiInput.js
- assets/js/synonyms/utils.js
- assets/js/utils/helpers.js
- includes/classes/Command.php
- includes/classes/Feature/Comments/Comments.php
- includes/classes/Feature/Facets/Widget.php
- includes/classes/Indexable.php
- includes/classes/Indexable/Comment/QueryIntegration.php
- includes/classes/Indexable/Comment/SyncManager.php
- includes/classes/Indexable/Post/Post.php
- includes/mappings/post/5-0.php
- includes/mappings/post/pre-5-0.php
With the update of 10up-toolkit, some lint rules started to trigger warnings. This PR fixes that.
Fixed: ES Lint warnings
> Fix some lint warnings

- assets/js/instant-results/admin/components/facet-selector.js
- assets/js/instant-results/components/common/checkbox-list.js
- assets/js/instant-results/components/common/checkbox.js
- assets/js/instant-results/components/common/modal.js
- assets/js/instant-results/components/common/panel.js
- assets/js/instant-results/components/common/small-button.js
- assets/js/instant-results/components/common/star-rating.js
- assets/js/instant-results/components/facets/facet.js
- assets/js/instant-results/components/facets/post-type-facet.js
- assets/js/instant-results/components/facets/price-range-facet.js
- assets/js/instant-results/components/facets/taxonomy-terms-facet.js
- assets/js/instant-results/components/layout/sidebar.js
- assets/js/instant-results/components/layout/toolbar.js
- assets/js/instant-results/components/results/pagination.js
- assets/js/instant-results/components/results/result.js
- assets/js/instant-results/components/tools/active-constraints.js
- assets/js/instant-results/functions.js
- assets/js/instant-results/hooks.js
- assets/js/instant-results/reducer.js
- assets/js/sync.js
- includes/classes/Command.php
> Lint JS and PHP for EP 4.0

- composer.json
- composer.lock
And run a composer update. This PR is part of the minimum PHP version bump for EP 4.0.0.
> Update the minimum PHP version in composer

- includes/classes/Indexable/Post/Post.php
- package-lock.json
- package.json
Changed - Updated jsdoc and fixed the documentation of the ep_thumbnail_image_size filter.
> jsdoc: Update and fix

- includes/classes/Indexable.php
This reverts commit 951110aa706b78ccfd663d24af07b630378e4cac.
#2567 Seemed to introduce a problem specific to WooCommerce that is affecting orders being fetched from all users in the My Account page. As it is a concerning issue, the fix for https://github.com/10up/ElasticPress/issues/1812 is going to be reverted.
Closes #2657 
Props @
> Revert "Remove old code that removed nested meta queries"

- CHANGELOG.md
- CREDITS.md
- elasticpress.php
- package-lock.json
- package.json
- readme.txt
This PR contains the changes scheduled for `4.0.1` release
Closes #
> Release 4.0.1

- CHANGELOG.md
- CREDITS.md
This is simply a partial update of the changelog and credits file with what we have merged so far.
The intent of this PR is to make it easier to identify what has already been added for the next release.
This should not need a changelog entry.
> Partial update of changelog and credits
